export const boookdata = [
    {
        "id ": "0",
        "bookName": "Kỹ Thuật Đánh Bóng Bàn",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-ky-thuat-danh-bong-ban.jpg?alt=media&token=5d94a54c-bf14-4a11-ae2d-58ab24cc7ce7",
        "price": "150000",
        "title": "Cùng với sự phát triển của kỹ thuật môn bóng bàn, sự biến hóa về đường bóng, biến hóa về điểm rơi khi đánh bóng cũng ngày một phát triển không ngừng. Điều này đòi hỏi vận động viên bóng bàn cần phải di chuyển bước chân nhanh hơn để đảm bảo tính chính xác của động tác chi trên và phát huy sở trường kỹ chiến thuật cá nhân. Ngược lại, nếu như di chuyển bước không tốt thì không thể đảm bảo cho chi trên thực hiện động tác đánh bóng chính xác. Tính chuẩn xác của bước chân và chất lượng đánh bóng có ảnh hưởng trực tiếp tới hiệu quảcủa việc sử dụng kỹ thuật sở trường của vận động viên. Vì vậy để đánh bóng bàn được tốt, nhất định phải nắm vững kỹ thuật di chuyển bước.",
        "category": "Thể Thao - Nghệ Thuật",
        "author": "Thanh Long",
    },
    {
        "id ": "1",
        "bookName": "Mỹ Thuật Vẽ Chân Dung",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/M%E1%BB%B9%20Thu%E1%BA%ADt%20V%E1%BA%BD%20Ch%C3%A2n%20Dung.jpg?alt=media&token=cd70e223-c821-4e8c-9294-a8a27ee76326",
        "price": "120000",
        "title": "Quyển sách Mỹ Thuật Vẽ Chân Dung sẽ hướng dẫn người học cách cảm nhận về vẽ chân dung thông qua những bài học cụ thể:",
        "category": "Thể Thao - Nghệ Thuật",
        "author": "Gia Bảo",
    },
    {
        "id ": "2",
        "bookName": "Thư Pháp Việt  Lý Thuyết Và Thực Hành",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/Th%C6%B0%20Ph%C3%A1p%20Vi%E1%BB%87t%20%E2%80%93%20L%C3%BD%20Thuy%E1%BA%BFt%20V%C3%A0%20Th%E1%BB%B1c%20H%C3%A0nh.jpg?alt=media&token=e60d414e-5dee-4ebb-8d21-901f49a824ab",
        "price": "100000",
        "title": "Trong tập sách này, Đăng Học phác thảo những sơ khởi về lí luận thư pháp Việt. Bằng kinh nghiệm, kiến thức của mình, ông đã tìm tòi và sáng tạo, mạnh dạng đưa ra phương pháp thực hành, cũng như phân loại các thể chữ như (Điền thể, Thủy thể, Mộc thể, Phong thể, Biến thể) và cách cảm nhận về tác phẩm thư pháp Việt. Bút một núi vượt gian truân khổ luyện Giấy cả rừng lót bước đến thành công Mực đầy sông chở con đò tri thức Đưa ta về bờ bến của thăng hoa.",
        "category": "Thể Thao - Nghệ Thuật",
        "author": "Đăng Học",
    },
    {
        "id ": "3",
        "bookName": "Học Chơi Cờ Tướng",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/H%E1%BB%8Dc%20Ch%C6%A1i%20C%E1%BB%9D%20T%C6%B0%E1%BB%9Bng.jpg?alt=media&token=910b5205-acc8-4556-9967-ee2e8887ab74",
        "price": "70000",
        "title": "Học chơi cờ tướng dưới đây cung cấp những thông tin hữu ích, thú vị về nguồn gốc cũng như những thủ thuật, kỹ xảo khi chơi cờ tướng, cuốn sách còn tập hợp những thế cờ tiêu biểu, đặc sắc kèm theo những hình ảnh minh họa giúp bạn đọc tiện theo dõi, thưởng thức và học tập. Mời các bạn cùng tham khảo bộ môn nghệ thuật thú vị mang nét di sản tinh thần quý báu của dân tộc thông qua quyển sách này.Cờ tướng là một bộ phận của văn hóa trung hoa và nhân loại từ hàng nghìn năm nay và cũng là một thú vui giải trí.",
        "category": "Thể Thao - Nghệ Thuật",
        "author": "Hải Phong",
    },
    {
        "id ": "4",
        "bookName": "Hướng Dẫn Chơi Cờ Vây",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/H%C6%B0%E1%BB%9Bng%20D%E1%BA%ABn%20Ch%C6%A1i%20C%E1%BB%9D%20V%C3%A2y.jpg?alt=media&token=a03d74d8-af2b-4e2a-a65e-1119905235ee",
        "price": "70000",
        "title": "Cờ Vây là trò để giải trí, thư giãn, vui vầy cùng bè bạn hay những người thân trong gia đình. Cờ Vây cũng là môn thể thao được tổ chức thành các giải đấu. Tiếp theo những thành tích vẻ vang của cờ Vua và cờ Tướng trên đấu trường quốc tế, chúng ta hy vọng rằng cờ vây cũng sẽ góp phần làm vẻ vang cho thể thao nước nhà.",
        "category": "Thể Thao - Nghệ Thuật",
        "author": "Nhiều Tác Giả",
    },
    {
        "id ": "5",
        "bookName": "Dạy Trẻ Tập Bơi",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-day-tre-tap-boi.jpg?alt=media&token=4c76ee8a-7e53-4f54-864b-80f4cb67bc1e",
        "price": "80000",
        "title": "Bơi lội là một kỹ năng cần thiết giúp đảm bảo an toàn cho trẻ khi tiếp xúc với nước, đồng thời giúp trẻ phát triển tốt về mặt thể chất và tinh thần. Cuốn sách “Dạy trẻ tập bơi” cung cấp nhiều lời khuyên cho luyện tập thực tế bà các biện pháp áp dụng nhằm đảm bảo tính ổn định của kỹ thuật. Cuốn sách đưa ra hình thức học tập và rèn luyện đúng đắn để bảo đảm các em có kỹ thuật bơi vững, thay đổi linh hoạt và đa dạng.",
        "category": "Thể Thao - Nghệ Thuật",
        "author": "Alis Mark",
    },
    {
        "id ": "6",
        "bookName": "Võ Thuật Trung Hoa  Đao Thuật",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/V%C3%B5%20Thu%E1%BA%ADt%20Trung%20Hoa%20%E2%80%93%20%C4%90ao%20Thu%E1%BA%ADt.jpg?alt=media&token=04aaab8c-2e8d-4884-a2a6-da7b6b7d6289",
        "price": "60000",
        "title": "Bộ sách “Võ thuật Trung Hoa” gồm 5 tập là những động tác từ cơ bản của tay và chân đến sử dụng thành thạo các dụng khí như đao thuật, kiếm thuật, côn thuật và giáo thuật. Để những người yêu thích và đam mê võ thuật luyện tập một cách thuận lợi nhất dễ học và dễ tập luyện.",
        "category": "Thể Thao - Nghệ Thuật",
        "author": "Hà Sơn",
    },
    {
        "id ": "7",
        "bookName": "Hướng Dẫn Học Karate",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/H%C6%B0%E1%BB%9Bng%20D%E1%BA%ABn%20H%E1%BB%8Dc%20Karate.jpg?alt=media&token=779ed282-0c0f-460e-af0b-fe86093006ff",
        "price": "70000",
        "title": "Từ Karate hiểu theo nghĩa đen là tay không. Các vũ khí chủ yếu của Karate là tay và chân. Tuy nhiên, một người giỏi Karate sẽ không chỉ đơn thuần dùng sức mạnh của chúng. Về mặt thể chất, việc luyện tập Karate không chỉ có ý nghĩa giúp cơ thể cường tráng, nâng cao tốc độ, sức mạnh và sự nhạy bén và ý thức tự cường. Và kết quả là người võ sinh có thể sẽ trở nên tự tin hơn  tự tin trong mối quan hệ với thế giới xung quanh mình",
        "category": "Thể Thao - Nghệ Thuật",
        "author": "Ts. Trần Tuấn Hiếu",
    },
    {
        "id ": "8",
        "bookName": "Cờ Tướng Những Phương Pháp Khai Cục Mới Nhất",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/C%E1%BB%9D%20T%C6%B0%E1%BB%9Bng%20Nh%E1%BB%AFng%20Ph%C6%B0%C6%A1ng%20Ph%C3%A1p%20Khai%20C%E1%BB%A5c%20M%E1%BB%9Bi%20Nh%E1%BA%A5t.jpg?alt=media&token=5b510c4c-7122-4876-8a09-bf8fe80f6896",
        "price": "80000",
        "title": "Trong cờ tướng có 3 giai đoạn: khai cục, trung cục và tàn cục. Giai đoạn khai cục có vai trò rất quan trọng và đôi khi có ảnh hưởng tới quyền quyết định tới sự thành bại của ván đấu.",
        "category": "Thể Thao - Nghệ Thuật",
        "author": "Hoàng Thiếu Long",
    },
    {
        "id ": "9",
        "bookName": "Tự Học Bơi Lội  Các Bước Đến Thành Công",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-tu-hoc-boi-loi-cac-buoc-den-thanh-cong.jpg?alt=media&token=ac4d2e22-822d-42dd-bd40-2f2b194e1e73",
        "price": "80000",
        "title": "Sách dạy tự học bơi, có hình minh họa đầy đủ, mong rằng cuốn sách sẻ giúp ích cho các bạn muốn tự học bơi, chúc các bạn thành công .",
        "category": "Thể Thao - Nghệ Thuật",
        "author": "David G. Thomas,Ms",
    },
    {
        "id ": "10",
        "bookName": "Công Nghệ Blockchain",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/C%C3%B4ng%20Ngh%E1%BB%87%20Blockchain.jpg?alt=media&token=197e1971-875e-4247-8abe-2f8f14ab5795",
        "price": "100000",
        "title": "Blockchain là chủ đề đang vô cùng nóng trên toàn cầu hiện nay. Nó cùng vớiBitcoinvà tiền kỹ thuật số trở thành đề tài bàn luận trên rất nhiều mặt báo và trong những cuộc trò chuyện của mọi người. Tuy nhiên, khi nói về blockchain vẫn còn nhiều tranh cãi. Có người lo lắng rằng Bitcoin có thể chỉ là bong bóng, nhiều người cho rằng công nghệ phía sau nó là một sự đột phá, và công nghệ ấy sẽ tiếp tục con đường của mình cho đến khi được chấp nhận và tích hợp với Internet.",
        "category": "Công Nghệ Thông Tin",
        "author": "Nhiều tác giả",
    },
    {
        "id ": "11",
        "bookName": "Machine Learning Cơ Bản",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-machine-learning-co-ban.jpg?alt=media&token=0a2292d1-8869-4d25-99b4-40271f16b4cf",
        "price": "110000",
        "title": "Những năm gần đây, AI  Artificial Intelligence (Trí Tuệ Nhân Tạo), và cụ thể hơn là Machine Learning (Học Máy hoặc Máy Học) nổi lên như một bằng chứng của cuộc cách mạng công nghiệp lần thứ tư (1  động cơ hơi nước, 2  năng lượng điện, 3  công nghệ thông tin). Trí Tuệ Nhân Tạo đang len lỏi vào mọi lĩnh vực trong đời sống mà có thể chúng ta không nhận ra. Xe tự hành của Google và Tesla, hệ thống tự tag khuôn mặt trong ảnh của Facebook, trợ lý ảo Siri của Apple, hệ thống gợi ý sản phẩm của Amazon, hệ thống gợi ý phim của Netflix, máy chơi cờ vây AlphaGo của Google DeepMind, …, chỉ là một vài trong vô vàn những ứng dụng của AI/Machine Learning.",
        "category": "Công Nghệ Thông Tin",
        "author": "Vũ Hữu Tiệp",
    },
    {
        "id ": "12",
        "bookName": "Learning Vue.js 2",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/Learning%20Vue.js%202.jpg?alt=media&token=c2757ba0-6b08-41af-9c7c-383ed6a6c276",
        "price": "120000",
        "title": "Olga Filipova là một lập trình viên có kinh nghiệm trong phát triển fontend, chính vì vậy các nội dung được viết ra trong Learning Vue.js 2 là rất sát với thực tế. Bản thânOlga Filipova cũng đang quản lý một dự án về học trực tuyến, do vậy các phần trong sách được kiến trúc có tính sư phạm cao. Với mỗi vấn đề đều có phần dẫn dắt và các ví dụ thực hành giúp cho việc nắm bắt các kiến thức framework Vue.js 2 trở lên dễ dàng.",
        "category": "Công Nghệ Thông Tin",
        "author": "Olga Filipova",
    },
    {
        "id ": "13",
        "bookName": "Laravel 5 Cookbook Enhance Your Amazing Applications",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/Laravel%205%20Cookbook%20Enhance%20Your%20Amazing%20Applications.jpg?alt=media&token=1942cb71-4375-460d-8c90-3213ee2bc911",
        "price": "150000",
        "title": "Learning Laravel 5: Building Practical Applications is the easiest way to learn web development using Laravel. Throughout 5 chapters, instructor Nathan Wu will teach you how to build many real-world applications from scratch. This bestseller is also completely about you. It has been structured very carefully, teaching you all you need to know from installing your Laravel 5.1 app to deploying it to a live server.",
        "category": "Công Nghệ Thông Tin",
        "author": "Nathan Wu",
    },
    {
        "id ": "14",
        "bookName": "Linux All-In-One For Dummies  5Th Edition",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/Linux%20All-In-One%20For%20Dummies%20%E2%80%93%205Th%20Edition.jpg?alt=media&token=9cdde094-9809-484e-988e-4502b0dc1b8c",
        "price": "200000",
        "title": "Linux All-in-One For Dummiesgiải thích mọi thứ bạn cần để bắt đầu và chạy với hệ điều hành Linux phổ biến. Được viết trong phong cách thân thiện và dễ tiếp cận, cuốn sách lý tưởng cho người mới dùng Linux và người đã có một ít kinh nghiệm với hệ điều hành này, cũng như bất kỳ ai đang học chứng chỉ Linux cấp độ 1. Bốn phần bên trong sách bao gồm các vấn đề cơ bản của Linux, làm sao để tương tác với nó, các vấn đề về mạng, dịch vụ Internet, quản trị, bảo mật, kịch bản scripting và chứng chỉ cấp 1.",
        "category": "Công Nghệ Thông Tin",
        "author": "Emmett Dulaney",
    },
    {
        "id ": "15",
        "bookName": "Giải Thuật Và Lập Trình",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/Gi%E1%BA%A3i%20Thu%E1%BA%ADt%20V%C3%A0%20L%E1%BA%ADp%20Tr%C3%ACnh.jpg?alt=media&token=b5ec066f-9ec2-4dd2-95db-c51d9c15a00e",
        "price": "120000",
        "title": "Nếu bạn là người đam mê tin học, nếu bạn là người muốn khám phá về lập trình, hẳn bạn phải biết đến một cuốn sách tin học rất nổi tiếng ở Việt Nam trong nhiều năm trở lại đây. Từ những học sinh không chuyên đến những thành viên đội tuyển thi quốc tế tin học, có lẽ không một ai chưa từng học qua cuốn sách được biên soạn bởi một thầy giáo trẻ những đầy tài năng của trường Đại học Sư phạm Hà Nội, thầy Lê Minh Hoàng.",
        "category": "Công Nghệ Thông Tin",
        "author": "Lê Minh Hoàng",
    },
    {
        "id ": "16",
        "bookName": "Programming ASP.NET MVC 4",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/Programming%20ASP.NET%20MVC%204.jpg?alt=media&token=bd4483f4-c58c-48d1-8fb7-643bea9e64c9",
        "price": "290000",
        "title": "Get up and running with ASP.NET MVC 4, and learn how to build modern server-side web applications. This guide helps you understand how the framework performs, and shows you how to use various features to solve many real-world development scenarios you’re likely to face. In the process, you’ll learn how to work with HTML, JavaScript, the Entity Framework, and other web technologies.",
        "category": "Công Nghệ Thông Tin",
        "author": "Jess Chadwick - Todd Snyder - Hrusikesh Panda",
    },
    {
        "id ": "17",
        "bookName": "Pro ASP.NET MVC 5",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/Pro%20ASP.NET%20MVC%205.jpg?alt=media&token=fb42eec2-dba2-4fcd-ab9f-108041334dd4",
        "price": "300000",
        "title": "The ASP.NET MVC 5 Framework is the latest evolution of Microsoft’s ASP.NET web platform. It provides a high-productivity programming model that promotes cleaner code architecture, test-driven development, and powerful extensibility, combined with all the benefits of ASP.NET.",
        "category": "Công Nghệ Thông Tin",
        "author": "Adam Freeman",
    },
    {
        "id ": "18",
        "bookName": "Giáo Trình Thuật Toán (Introduction To Algorithms )",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/Gi%C3%A1o%20Tr%C3%ACnh%20Thu%E1%BA%ADt%20To%C3%A1n%20(Introduction%20To%20Algorithms%20).jpg?alt=media&token=42541db8-1091-4b01-bea7-428552dd6649",
        "price": "250000",
        "title": "Có nhiều quyển sách thuật toán được trình bày chặt chẽ nhưng không đầy đủ về nội dung, trong khi nhiều quyển khác chứa đựng nhiều nội dung nhưng lại thiếu sự chặt chẽ toán học. Introduction to Algorithms là một quyển sách kết hợp cả tính chặt chẽ và tính toàn diện về nội dung.",
        "category": "Công Nghệ Thông Tin",
        "author": "Thomas H. Cormen - Charles E. Leiserson,",
    },
    {
        "id ": "19",
        "bookName": "Php, Mysql, Javascript & Html5 All-In-One For Dummies",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/Php%2C%20Mysql%2C%20Javascript%20%26%20Html5%20All-In-One%20For%20Dummies.jpg?alt=media&token=441b00fa-321b-4787-8eba-5be1b245f870",
        "price": "200000",
        "title": "Get the basics on four key web programming tools in one great book! PHP, JavaScript, and HTML5 are essential programming languages for creating dynamic websites that work with the MySQL database. PHP and MySQL provide a robust, easy-to-learn, open-source solution for creating superb e-commerce sites and content management. JavaScript and HTML5 add support for the most current multimedia effects. This one-stop guide gives you what you need to know about all four! Seven self-contained minibooks cover web technologies, HTML5 and CSS3, PHP programming, MySQL databases, JavaScript, PHP with templates, and web applications.",
        "category": "Công Nghệ Thông Tin",
        "author": "Steve Suehring, Janet Valade",
    },
    {
        "id ": "20",
        "bookName": "Tự Học Tiếng Anh Hiệu Quả",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/T%E1%BB%B1%20H%E1%BB%8Dc%20Ti%E1%BA%BFng%20Anh%20Hi%E1%BB%87u%20Qu%E1%BA%A3.jpg?alt=media&token=39fb4115-c478-4d36-9166-2cfc250d5b65",
        "price": "150000",
        "title": "Nếu như bạn mong muốn giao tiếp tiếng Anh thành thạo, chuyên nghiệp từ 3 tới 6 tháng thì cuốn sách này sẽ làm bạn thất vọng. Thực tế cho thấy chưa có ai mới bắt đầu học tiếng Anh có thể giao tiếp được trôi chảy trong thời gian từ 3  6 tháng. Đó là ảo tưởng. Nhưng nếu như bạn đang tìm kiếm làm như thế nào có thể sử dụng tiếng Anh giao tiếp thành thạo, chuyên nghiệp trong 1 năm tới thì xin chúc mừng bạn. Tôi tin rằng những bí mật được tiết lộ trong cuốn sáchnày sẽ làm bạn thỏa mãn với điều đó.",
        "category": "Học Ngoại Ngữ",
        "author": "Nguyễn Thị Hà Bắc",
    },
    {
        "id ": "21",
        "bookName": "3000 Từ Vựng Tiếng Anh Thông Dụng Nhất",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/3000%20T%E1%BB%AB%20V%E1%BB%B1ng%20Ti%E1%BA%BFng%20Anh%20Th%C3%B4ng%20D%E1%BB%A5ng%20Nh%E1%BA%A5t.jpg?alt=media&token=2f06267f-e79a-4cc5-9f70-a9d9c6524b3f",
        "price": "200000",
        "title": "Từ vựng đóng một vai trò đặc biệt quan trọng, nhất là trong giao tiếp. Nhằm đáp ứng nhu cầu đó chúng tôi xin giới thiệu với bạn đọc cuốn3000 Từ vựng Tiếng Anh thông dụng nhất. Cuốn sách bao gồm 3000 từ vựng căn bản và thông dụng nhất nhằm giúp các bạn nâng cao vốn từ vựng của mình.",
        "category": "Học Ngoại Ngữ",
        "author": "Nhiều tác giả",
    },
    {
        "id ": "22",
        "bookName": "360 Động Từ Bất Quy Tắc Và 12 Thì Cơ Bản Trong Tiếng Anh",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/360%20%C4%90%E1%BB%99ng%20T%E1%BB%AB%20B%E1%BA%A5t%20Quy%20T%E1%BA%AFc%20V%C3%A0%2012%20Th%C3%AC%20C%C6%A1%20B%E1%BA%A3n%20Trong%20Ti%E1%BA%BFng%20Anh.jpg?alt=media&token=fc92fe46-7244-407a-a578-50406f541d05",
        "price": "210000",
        "title": "Cuốn sách này như một người bạn luôn nhắc nhở bạn dùng chính xác các dạng nguyên thể, quá khứ và phân từ của động từ. Mỗi động từ chúng tôi có đưa ra ví dụ để bạn có thể hiểu đươc cách dùng của động từ đó.để nhớ và dùng các động từ bất quy tắc này một cách tốt nhất các bạn lên học thuộc các ví dụ, từ đó các bạn sẽ nhớ được tình huống và vận dụng các động từ này một cách hiệu quả nhất",
        "category": "Học Ngoại Ngữ",
        "author": "Nhiều tác giả",
    },
    {
        "id ": "23",
        "bookName": "Ngữ Pháp Tiếng  Anh Ôn Thi Toeic",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/Ng%E1%BB%AF%20Ph%C3%A1p%20Ti%E1%BA%BFng%20Anh%20%C3%94n%20Thi%20Toeic.jpg?alt=media&token=9f0f2bc5-bcbe-488a-a7bd-6702c386f237",
        "price": "250000",
        "title": "Đây là “Hệ thống ngữ pháp” chuẩn của Bộ giáo dục ban hàng trong loạt hệ thống kiến thức trọng tâm họcônToeic hiệu quả. Đúng như tên gọi, mục lớn này nhằm giúpngười học biết, nắm bắt và hiểu một cách có hệ thống cácchuyên đề ngữ pháp chính cần có để hoàn thành tốtbài thiToeicmới với 2 phần chính là Nghe và Đọc.",
        "category": "Học Ngoại Ngữ",
        "author": "Bộ Giáo Dục và Đào tạo",
    },
    {
        "id ": "24",
        "bookName": "384 Tình Huống Thực Hành Đàm Thoại Tiếng Hàn",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-384-tinh-huong-thuc-hanh-dam-thoai-tieng-han.jpg?alt=media&token=30cb57e3-b95a-4ada-8c77-b7d93107889d",
        "price": "210000",
        "title": "Cuốn sách 384 tình huống thực hành đàm thoại tiếng Hàn với 192 mẫu câu cơ bản, ứng dụng được trong nhiều tình huống giao tiếp khác nhau. Mỗi mẫu câu đều có hai tình huống đàm thoại. Bạn nên học thuộc các mẫu câu đàm thoại này để hiểu cách vận dụng.",
        "category": "Học Ngoại Ngữ",
        "author": "Jung min kyung",
    },
    {
        "id ": "25",
        "bookName": "Ngữ Pháp Tiếng Hàn Cơ Bản",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/Ng%E1%BB%AF%20Ph%C3%A1p%20Ti%E1%BA%BFng%20H%C3%A0n%20C%C6%A1%20B%E1%BA%A3n.jpg?alt=media&token=2006a8df-6b03-488d-a1cd-0a3fdc1a4805",
        "price": "190000",
        "title": "NGỮ PHÁP CƠ BẢN TIẾNG HÀNcủa tác giả Lê Huy Khoa, hệ thống một cách đầy đủ, chính xác và khoa học nhất các kiến thức cơ bản về ngữ pháp tiếng Hàn như danh từ, động từ, tính từ…",
        "category": "Học Ngoại Ngữ",
        "author": "Lê Huy Khoa",
    },
    {
        "id ": "26",
        "bookName": "Kanji Look And Learn N3  N2: Bản Nhật Việt",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-kanji-look-and-learn-n3-n2-ban-nhat-viet.jpg?alt=media&token=1bdfd2f0-1465-4a26-bacd-126c741a0348",
        "price": "180000",
        "title": "Kanji look and learn N3, N2  Bản Nhật Việtđược biên soạn bắt nguồn từ quyển sách Kanji Pixtographic  là cuốn sách dạy Kanji ở trình độ trung cấp N3 và N2 bằng hình ảnh cực hay. Tuy nhiên điểm hạn chế của nó là trình bày không được khoa học như cuốn Kanji look and learn và hoàn toàn bằng tiếng Anh. Vậy nên, tác giả đã ghép lại các hình ảnh từ cuốn sách này và phối hợp ghép các hình ảnh có sẵn của quyển Kanji look and learn để tạo nên một quyển sách mới, hoàn toàn tiếng Việt với cách trình bày khoa học và vô cùng dễ học với cái tên là Kanji look and learn N23 phiên bản tiếng Việt",
        "category": "Học Ngoại Ngữ",
        "author": "NXB Từ Điển Bách Khoa",
    },
    {
        "id ": "27",
        "bookName": "Chinh Phục Bài Tập Từ Vựng Tiếng Anh",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/Chinh%20Ph%E1%BB%A5c%20B%C3%A0i%20T%E1%BA%ADp%20T%E1%BB%AB%20V%E1%BB%B1ng%20Ti%E1%BA%BFng%20Anh.jpg?alt=media&token=34444aeb-cd16-4ec5-b321-1a342bef6444",
        "price": "200000",
        "title": "CHINH PHỤC BÀI TẬP TỪ VỰNG TIẾNG ANH Cuốn sách “Chinh phục từ vựng Tiếng Anh” giúp các em học sinh chinh phục tốt phần từ vựng trong kì thi THPT Quốc gia, cũng như là tài liệu tốt để các em phục vụ cho kì thi IELTS, TOEFL, TOEIC.",
        "category": "Học Ngoại Ngữ",
        "author": "Lovebook",
    },
    {
        "id ": "28",
        "bookName": "Wir Lernen Deutsch  Chúng Ta Học Tiếng Đức",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/Wir%20Lernen%20Deutsch%20%E2%80%93%20Ch%C3%BAng%20Ta%20H%E1%BB%8Dc%20Ti%E1%BA%BFng%20%C4%90%E1%BB%A9c.jpg?alt=media&token=cdd00e98-98fd-4d65-82e0-9b24e5d3d54e",
        "price": "220000",
        "title": "Đây là cuốn sách hay dành cho cách bạn đang muốn tìm hiểu vào học tiếng Đức bao gồm cách đọc,ngữ pháp và từ vựng…, sách do chính tác giả Đặng Trung Ngọc gửi đến cho thư viện Sachvui.com của chúng ta!",
        "category": "Học Ngoại Ngữ",
        "author": "Đặng Trung Ngọc",
    },
    {
        "id ": "29",
        "bookName": "Cách Học Ngoại Ngữ Nhanh Và Không Bao Giờ Quên",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/C%C3%A1ch%20H%E1%BB%8Dc%20Ngo%E1%BA%A1i%20Ng%E1%BB%AF%20Nhanh%20V%C3%A0%20Kh%C3%B4ng%20Bao%20Gi%E1%BB%9D%20Qu%C3%AAn.jpg?alt=media&token=72184841-8d74-4c00-905f-c276f87117d0",
        "price": "210000",
        "title": "Fluent Forever là cách dạy bất cứ ngoại ngữ nào bạn muốn một cách nhanh nhất, hiệu quả nhất. Đây là tài liệu học ngoại ngữ được đánh giá cao nhất hiện nay trên toàn thế giới bới nó không đơn thuần là sách dạy ngoại ngữ mà là một cú đột phá tư duy xuất sắc để làm chủ não bộ. Ứng dụng tri thức về khoa học thần kinh, bạn không cần chờ đến một sự may mắn tình cờ hay cần mẫn quá sức để đưa thông tin cần thiết vào não bộ. Những gì bạn muốn sẽ thuận với tự nhiên lưu vào bộ nhớ. Bởi thế, không phải ngẫu nhiên, trang web fluent-forever.com trở thành một “hiện tượng mạng”, dạy ngoại ngữ cho 1,5 triệu người trên toàn thế giới và khiến hàng triệu người ham thích thử thách tư duy tìm đến.",
        "category": "Học Ngoại Ngữ",
        "author": "Gabriel Wyner",
    },
    {
        "id ": "30",
        "bookName": "Từ Điển Pháp  Việt",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/T%E1%BB%AB%20%C4%90i%E1%BB%83n%20Ph%C3%A1p%20%E2%80%93%20Vi%E1%BB%87t.jpg?alt=media&token=2a78803b-fb76-4d7b-91a0-36b3bf4aaba9",
        "price": "200000",
        "title": "Nhằm giúp bạn đọc biết nhiều hơn về một dân tộc đã giành được độc lập và tự do qua nhiều cuộc đấu tranh gian khổ cuốn Từ Điển Pháp Việt này đã được cho biên soạn.",
        "category": "Học Ngoại Ngữ",
        "author": "Hồ Hải Thụy - Chu Khắc Thuật",
    },
    {
        "id ": "31",
        "bookName": "Nguyễn Tứ",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-cac-kieu-kien-truc-tren-the-gioi.jpg?alt=media&token=6e0fdf2f-2fa6-48d8-b079-b4e2ba4e2425",
        "price": "170000",
        "title": "Các kiểu kiến trúc trên thế giới sẽ cho bạn đọc một bức tranh toàn cảnh về các công trình kiến trúc mà loài người đã tạo dựng nên theo trình tự lịch sử từ thời Trung cổ, phục hưng Châu Âu, thời đại công nghiệp và cho đến hiện đại ngày nay.",
        "category": "Kiến Trúc - Xây Dựng",
        "author": "Nguyễn Tứ",
    },
    {
        "id ": "32",
        "bookName": "Kiến Trúc Cổ Việt Nam Từ Cái Nhìn Khảo Cổ Học",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-kien-truc-co-viet-nam-tu-cai-nhin-khao-co-hoc.jpg?alt=media&token=2244d80e-1b98-4c56-b3a3-d4f2711cbc63",
        "price": "170000",
        "title": "Nhà xuất bản: NXB   Xây dựng  Năm xuất bản: 2007     Số trang: 179",
        "category": "Kiến Trúc - Xây Dựng",
        "author": "Trịnh Cao Tưởng",
    },
    {
        "id ": "33",
        "bookName": "Kim Loại Trong Nghệ Thuật Trang Trí Nội Ngoại Thất  Các Loại Cầu Thang, Tường Rào, Lan Can",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-kim-loai-trong-nghe-thuat-trang-tri-noi-ngoai-that-cac-loai-cau-thang-tuong-rao-lan-can.jpg?alt=media&token=bc04e6b8-de3e-45b2-a8d8-cc45f2270665",
        "price": "200000",
        "title": "Trong nghệ thuật trang trí nội thất, ngoại thất từ xa xưa, chúng ta thường thích sử dụng gỗ như chất liệu chính vừa gọn nhẹ vừa dễ cưa xẻ, đục, chạm, lắp ghép… Thuận tiện hơn cả là sử dụng luôn chất liệu xây dựng như gạch, đá, vữa hồ để tạo nên từ chiếc cầu thang, lan can đến hàng rào…",
        "category": "Kiến Trúc - Xây Dựng",
        "author": "Nguyễn Kim Dân",
    },
    {
        "id ": "34",
        "bookName": "How To Draw",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-how-to-draw.jpg?alt=media&token=d1f4bdfa-8b65-449a-9928-2a1b909a81f2",
        "price": "190000",
        "title": "How to Draw is for artists, architects and designers. It is useful to the novice, the student and the professional. You will learn how to draw any object or environment from your imagination, starting with the most basic perspective drawing skills.",
        "category": "Kiến Trúc - Xây Dựng",
        "author": "Scott Robertson - Thomas Bertling",
    },
    {
        "id ": "35",
        "bookName": "Sức Bền Vật Liệu Và Kết Cấu",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-suc-ben-vat-lieu-va-ket-cau.jpg?alt=media&token=c83122f9-751e-4c58-b271-82a5f43a1189",
        "price": "170000",
        "title": "Sức bền vật liệu là môn học cơ sở quan trọng, cung cấp cho người học những kiến thức cơ bản nhất để giải các bài toán liên quan đến hệ thanh, tính toán sức bền của vật liệu và kết cấu. Chính vì vậy sức bền vật liệu và cơ học kết cấu được giảng dạy cho sinh viên tất cả các trường đại học kỹ thuật",
        "category": "Kiến Trúc - Xây Dựng",
        "author": "Nguyễn Đình Đức - Đào Như Mai",
    },
    {
        "id ": "36",
        "bookName": "Định Mức Dự Toán Xây Dựng Công Trình  Phần Khảo Sát Xây Dựng",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-dinh-muc-du-toan-xay-dung-cong-trinh-phan-khao-sat-xay-dung.jpg?alt=media&token=0bc15c96-02ee-41f4-97ca-e61f796e76ba",
        "price": "190000",
        "title": "Trình bày các quy định định mức dự toán các công tác khảo sát xây dựng. Hướng dẫn việc lập đơn giá khảo sát và quản lý chi phí khảo sát xây dựng. Ban hành kèm theo quyết định số 28/2005/QĐ-BXD ngày 10/8/2005 của Bộ trưởng Bộ Xây dựng.",
        "category": "Kiến Trúc - Xây Dựng",
        "author": "Bộ Xây Dựng",
    },
    {
        "id ": "37",
        "bookName": "Định Mức Dự Toán Xây Dựng Công Trình  Phần Lắp Đặt",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-dinh-muc-du-toan-xay-dung-cong-trinh-phan-lap-dat.jpg?alt=media&token=025579b8-43ee-411d-9337-78c87469548d",
        "price": "180000",
        "title": "Ebook Định mức dự toán xây dựng công trình (Phần lắp đặt) trình bày nội dung định mức xây dựng về lắp đặt hệ thống công trình ống và phụ tùng ống, bảo ôn đường ống, phụ tùng và thiết bị khai thác nước ngầm. Mời các bạn cùng tham khảo để nắm nội dung cụ thể.",
        "category": "Kiến Trúc - Xây Dựng",
        "author": "Bộ Xây Dựng",
    },
    {
        "id ": "38",
        "bookName": "Thiết Kế Đường Ô Tô : Tập 4",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-thiet-ke-duong-o-to-tap-4.jpg?alt=media&token=2f484ce5-d6c2-447b-a413-9ee33f5fda05",
        "price": "120000",
        "title": "Giáo trình Thiết kế đường ô tô (Tập 4) trình bày những nội dung về công tác khảo sát thiết kế đường ôtô ở các giai đoạn khác nhau; trong đó trình bày kỹ nội dung và phương pháp điều tra giao thông, phương pháp phân tích hiệu quả kinh tế và đánh giá các phương án thiết kế; phương pháp thiết kế bình đồ, trắc dọc, trắc ngang và đặc điểm công tác khảo sát thiết kế đường trong các điều kiện thiên nhiên khác nhau.",
        "category": "Kiến Trúc - Xây Dựng",
        "author": "Dương Ngọc Hải",
    },
    {
        "id ": "39",
        "bookName": "Nghệ Thuật Kiến Trúc Theo Văn Hóa Cổ Trung Hoa",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-nghe-thuat-kien-truc-theo-van-hoa-co-trung-hoa.jpg?alt=media&token=2770a882-6153-4830-b67b-4642e3ded20f",
        "price": "140000",
        "title": "Màu sắc, ánh sáng và bố trí đồ đạc trong nội thất còn ảnh hưởng đếntinh thần và sức khỏe. Với màu sơn ấm áp của một căn phòng, người sống trong đấy cảm thấy không gian ấm cúng hơn. Việc thiết kế hệ thống ánh sáng khéo léo và thích hợp, người sử dụng sẽ cảm thấy thoải mái và tránh được ánh sáng chóị Với các chất liệu đánh bóng nội thất phối hợp tốt người sử dụng sẽ cảm nhận các kết cấu và văn hoa được tạo ra",
        "category": "Kiến Trúc - Xây Dựng",
        "author": "Nguyễn Hoàng Hải",
    },
    {
        "id ": "40",
        "bookName": "Lịch Sử Kiến Trúc Thế Giới  Quyển 1",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-lich-su-kien-truc-the-gioi-quyen-1.jpg?alt=media&token=c6525143-0d97-48ed-8d0a-ad7d8fecac6b",
        "price": "175000",
        "title": "Cuốn sách sẻ giới thiêu đến bạn đọc các kiểu kiến trúc nổi tiếng trên thế giới , giúp các bạn có cái nhìn khái quát hơn về kiến trúc cũng như lịch sự của nó , mong rằng cuốn sách sẻ mang lại nhiều thông tin bổ ích cho các bạn .",
        "category": "Kiến Trúc - Xây Dựng",
        "author": "Trần Trọng Chi",
    },
    {
        "id ": "41",
        "bookName": "Kinh Doanh Trực Tuyến",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/kinh-doanh-truc-tuyen.jpg?alt=media&token=7c664858-6239-4c8d-a876-a865736bf96b",
        "price": "190000",
        "title": "Khác với kinh doanh truyền thống đòi hỏi một lượng vốn lớn và nguồn lực khổng lồ để xâm nhập thị trường và cạnh tranh để tồn tại, một Facebook bé nhỏ thoắt vươn vai thành người khổng lồ từ căn buồng ký túc xá của những chàng sinh viên không có gì ngoài đam mê và hoài bão. Kỷ nguyên công nghệ số đang tạo ra những sân chơi với cơ hội công bằng hơn cho doanh nghiệp vừa và nhỏ, doanh nghiệp mới khởi nghiệp. Có một website, một blog hay thậm chí là một gian hàng trực tuyến và một mô hình kinh doanh tốt, bạn đã có thể bán hàng.",
        "category": "Marketing - Bán hàng",
        "author": "Nguyễn Đặng Tuấn Minh",
    },
    {
        "id ": "42",
        "bookName": "Nghệ thuật bán hàng bậc cao",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nghe-thuat-ban-hang-bac-cao.jpg?alt=media&token=01d33a44-b910-4795-9c9d-55c6b57fb8a5",
        "price": "200000",
        "title": "Triết lý chứa đựng trong cuốn sáchNghệ thuật bán hàng bậc caothật đơn giản: “Bạn có thể có được những tất cả mọi thứ trong cuộc sống nếu bạn biết giúp người khác đạt được điều họ muốn”, thậm chí còn đúng đắn và cần thiết hơn trong cuộc sống hiện nay so với thời kỳ khi cuốn Nghệ Thuật Bán Hàng Bậc Cao được xuất bản lần đầu. Mục tiêu cuả một thương vụ là đảm bảo khách hàng nhận được giá trị tương xứng, nhưng nếu bạn mang đến cho khách hàng những giá trị còn cao hơn giá trị mà lẽ ra họ sẽ nhận được thì không những bạn đã có một thương vụ thành công mà bạn còn có thêm một khách hàng sẵn lòng giúp bạn có thêm nhiều khách hàng khác nữa.",
        "category": "Marketing - Bán hàng",
        "author": "Zig Ziglar",
    },
    {
        "id ": "43",
        "bookName": "Nghệ Thuật Lấy Lòng Khách Hàng",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-nghe-thuat-lay-long-khach-hang.jpg?alt=media&token=9058d685-4fd5-4550-8898-10839b66ce3f",
        "price": "190000",
        "title": "Nghệ thuật lấy lòng khách hàngcủaMichael J. Maherlà một cuốn sách mà những người làm kinh doanh không thể bỏ qua.",
        "category": "Marketing - Bán hàng",
        "author": "Michael J. Meher",
    },
    {
        "id ": "44",
        "bookName": "Pr Là Sống",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-pr-la-song.jpg?alt=media&token=c9a60286-68a8-4b8f-9f01-3022b1e59da1",
        "price": "200000",
        "title": "PR là một chức năng quản trị định hướng thái độ của công chúng, xác định chính sách, thực hiện và làm cho quan tâm một tổ chức, được thực hiện theo một chương trình hành động tìm kiếm sự thông hiểu và chấp nhận của công chúng” theo lời một nữ chuyên gia PR định nghĩa.",
        "category": "Marketing - Bán hàng",
        "author": "Phạm Quốc Hưng",
    },
    {
        "id ": "45",
        "bookName": "Tăng Tốc Bán Hàng Bằng Spin",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-tang-toc-ban-hang-bang-spin.jpg?alt=media&token=e2c7e1a5-af48-48e9-a1ed-77ee929a811e",
        "price": "300000",
        "title": "Đã có rất nhiều cuốn sách viết về bán hàng. Mỗi cuốn lại tiếp cận bán hàng theo những khía cạnh và cách thức khác nhau. Nhưng khác với các cuốn sách về bán hàng,Tăng tốc bán hàng bằng Spincủa tác giả Neil Rackham không nói về nghệ thuật bán hàng thông qua các bí kíp mà đưa ra mô hình chuỗi câu hỏi SPIN (viết tắt của Situation questions, Priblem questions, Implication quesstions, Need-payoff questions hay còn gọi là các câu hỏi Tình hình, câu hỏi Vấn đề, câu hỏi Gợi ý và câu hỏi Chi phí nhu cầu). Cuốn sách không phải là lý thuyết sáo rỗng về cách bán hàng mà là những nghiên cứu hết sức khoa học và cụ thể của Huthwaite-công ty chuyên nghiên cứu về phương pháp bán hàng hiệu quả của Neil Rackham.",
        "category": "Marketing - Bán hàng",
        "author": "Neil Rackham",
    },
    {
        "id ": "46",
        "bookName": "Bí Quyết Thành Công 100 Thương Hiệu Hàng Đầu Thế Giới",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-bi-quyet-thanh-cong-100-thuong-hieu-hang-dau-the-gioi.jpg?alt=media&token=99cacf21-cb15-4440-8f18-d108fac48d5e",
        "price": "250000",
        "title": "Brand Royalty  Bí Quyết Thành Công 100 Thương Hiệu Hàng Đầu Thế Giớilà một quyển cẩm nang độc đáo và hữu ích trong giai đoạn hiện nay. Quyển sách không chỉ đóng vai trò là xác định và bình chọn các thương hiệu thành công nổi tiếng hàng đầu dựa trên các tiêu chí đánh giá căn bản như: thành công về mặt tài chính, tần số quảng cáo, chất lượng thương hiệu, mức độ trường tồn của thương hiệu, các chiến lược sáng tạo mới, những thành quả đột phá mang tính toàn cầu… mà còn đóng vai trò như một tuyển tập đầy đủ nhất về những câu chuyện đi  đến  thành  công của những thương hiệu xuất sắc nhất, ví như:Adidas, Zippo, Sony, Coca Cola, Pepsi, Microsoft,Nike, Rolex, Toyota, Mercedes  Benz, Yamaha…cùng với những phân tích, nhận định sâu sắc về các bí quyết đằng sau những thành công rực rỡ đó, và truy tìm ra những điểm then chốt giúp cho các thương hiệu này trở nên độc đáo và đi vào lòng người. Qua đó, sách còn giúp rút ra những bài học bổ ích cho tất cả công ty khác để áp dụng thành công trong việc xây dựng thương hiệu và kinh doanh hiệu quả.",
        "category": "Marketing - Bán hàng",
        "author": "Matt Haig",
    },
    {
        "id ": "47",
        "bookName": "Marketing Truyền Miệng",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-marketing-truyen-mieng.jpg?alt=media&token=3ba771dd-a34d-4cc0-b034-2f08296e233b",
        "price": "210000",
        "title": "Quảng cáo luôn là phần khó khăn nhất trong một chiến dịch quảng cáo sản phẩm mới, nó quyết định danh tiếng cũng như sự tồn tại của công ty. Có hàng tá các phương pháp để marketing tuy nhiên đâu mới là phương pháp marketing hiệu quả mà ít tốn kém ? Câu trả lời nằm trong cuốn“Marketing truyền miệng”.",
        "category": "Marketing - Bán hàng",
        "author": "Andy Sernovitz",
    },
    {
        "id ": "48",
        "bookName": "Vua Bán Lẻ",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-vua-ban-le.jpg?alt=media&token=f6a581a6-cb30-40f6-8ebd-ad1b65781d8b",
        "price": "170000",
        "title": "Cạnh tranh trong lĩnh vực bán lẻ mỗi năm lại càng thêm gắt gao hơn. Ngày nay khách hàng có nhiều sự lựa chọn hơn bao giờ hết, và họ cũng kén chọn nơi mua hơn. Vạn người bán, may ra mới có trăm người mua  chưa kể người mua càng ngày lọc lõi và thông thái hơn; vậy nên cũng không có gì đáng ngạc nhiên khi một số tên tuổi lớn trong ngành bán lẻ gần đây ở Mỹ cứ thi nhau sụp đổ. Từ Merry-Go-Round và eToys cho tới Service Merchandise và Woolworth, chiến trường bán lẻ giờ rải đầy xác của những vị anh hùng bại trận. Một thời từng là ngôi sao sáng trên bầu trời kinh doanh, những cựu thủ lĩnh thị trường này đã rơi từ đỉnh cao danh vọng tiền tài xuống đống tro tàn nhanh tới mức họ còn không kịp nhận ra điều gì đã đẩy họ xuống.",
        "category": "Marketing - Bán hàng",
        "author": "Willard N Ander - Neil Z Stern",
    },
    {
        "id ": "49",
        "bookName": "Nghệ Thuật Chinh Phục Khách Hàng",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-nghe-thuat-chinh-phuc-khach-hang.jpg?alt=media&token=441d3ad5-8823-4e68-b2b7-42894e5ccc43",
        "price": "180000",
        "title": "TrongNghệ thuật Chinh Phục Khách Hàngbậc thầyJanelle Barlow và Claus Mollerđã giới thiệu một ý tưởng đột phá mang tính cách mạng: Biến những lời phàn nàn, chỉ trích thành một món quà. Thật vậy, lời phàn nàn của khách hàng là thông tin phản hồi quý báu có thể giúp các doanh nghiệp cải thiện chất lượng sản phẩm, nâng cấp dịch vụ, ứng xử của con người và xác định trọng tâm định hướng sản xuất, kinh doanh, thị trường một cách nhanh chóng, hiệu quả và ít tốn kém nhất.",
        "category": "Marketing - Bán hàng",
        "author": "Janelle Barlow",
    },
    {
        "id ": "50",
        "bookName": "Bán Hàng Tức Thì",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-ban-hang-tuc-thi.jpg?alt=media&token=c577f244-5742-4e5b-b934-289b1582c817",
        "price": "190000",
        "title": "Bạn sẽ học được các kỹ năng thông qua những ví dụ minh hoạ cụ thể đã được thực tế chứng minh, được tiếp cận từng bước với quy trình bán hàng và các nguyên tắc giải quyết khó khăn, được học cách để gây ấn tượng tốt đẹp trong lần tiếp xúc đầu tiên với khách hàng. Bạn sẽ biết cách biến những người thờ ơ nhất thành khách hàng của bạn và còn nhiều, nhiều hơn thế nữa…",
        "category": "Marketing - Bán hàng",
        "author": "Cyril Charney",
    },
    {
        "id ": "51",
        "bookName": "Những Sự Thật  Làm Giàu Từ Mạng Xã Hội",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-nhung-su-that-lam-giau-tu-mang-xa-hoi.jpg?alt=media&token=b4511e2a-689e-4deb-bde8-a640e6069acf",
        "price": "210000",
        "title": "“Những Sự Thật  Làm Giàu Từ Mạng Xã Hội”dành cho bất cứ ai muốn khai thác sức mạnh của mạng xã hội nhằm phục vụ công việc. Những người làm marketing, quan hệ công chúng, các chủ doanh nghiệp nhỏ, những người đã đi làm, những người tìm việc, những người gây quỹ, và các nhà hoạt động xã hội đều có thể tìm thấy những cách thức để thu lợi từ mạng xã hội mang tính chiến lược từ cuốn sách này. Cuốn sách mang đến cho bạn những kiến thức nền tảng về mạng xã hội, giúp bạn hiểu biết hơn về những xu hướng trong tương lai, và khuyến khích bạn suy nghĩ một cách chiến lược về cách thức tốt nhất mà bạn có thể thúc đẩy sức mạnh của mạng xã hội nhằm củng cố, nâng cao công việc, động cơ, mục tiêu và cuộc sống của mình.",
        "category": "Marketing - Bán hàng",
        "author": "Patrice - Anne Rutledge",
    },
    {
        "id ": "52",
        "bookName": "Chat Với René Descartes",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-chat-voi-rene-descartes.jpg?alt=media&token=446872f4-f9e3-47e5-a4a5-dce2a3be151b",
        "price": "190000",
        "title": "Một cuộc trò chuyện giả tưởng giữa tác giả cùng với René René Descartes  một nhà toán học; một triết gia lỗi lạc, được xem là cha đẻ của triết học hiện đại. Cách viết hài hước, giải thích những tư tưởng của Descartes một cách đơn giản, giúp bạn đọc tiếp cận với triết học của học giả lớn dễ dàng hơn. Và qua đó, bạn đọc cũng có thể hiểu thêm về Descartes, một con người lánh đời, luôn mang nhiều ước vọng và luôn nỗ lực để phá bỏ sự chi phối hoàn toàn của phái Kinh viện trong Triết học.",
        "category": "Triết Học",
        "author": "Bùi Văn Nam Sơn",
    },
    {
        "id ": "53",
        "bookName": "Siêu Lý Tình Yêu",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-sieu-ly-tinh-yeu.jpg?alt=media&token=110bd6c5-46b8-4f5f-9aeb-91d4cbaa7668",
        "price": "170000",
        "title": "Soloviev chỉ ra 5 loại quan hệ nam nữ với loại quan hệ nam nữ có tình yêu gắn với lý tưởng hóa đối tượng yêu, làm chúng ta khi yêu mang bản nguyên thần thánh. Tình yêu nam  nữ tuyệt đích sẽ bất tử hóa tất cả bởi tình yêu chuyên trở sự sống vĩnh cửu cho cái mình yêu, tái sinh vĩnh viễn trong cái đẹp.",
        "category": "Triết Học",
        "author": "Vladimir Soloviev",
    },
    {
        "id ": "54",
        "bookName": "Cuộc Cách Mạng Ngược Trong Khoa Học",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-cuoc-cach-mang-nguoc-trong-khoa-hoc.jpg?alt=media&token=55412eed-8548-4080-84a6-9fc528d386f5",
        "price": "200000",
        "title": "“Cuộc Cách Mạng Ngược Trong Khoa Học” là tác phẩm Hayek trình bày đầy đủ nhất quan điểm của ông về hệ thống phương pháp luận trong lĩnh vực khoa học xã hội. Cuốn sách gồm ba phần, tương đương với ba bài luận được ông đăng trên chuyên san Economica trong giai đoạn 1941-1944.",
        "category": "Triết Học",
        "author": "Friedrich August Hayek",
    },
    {
        "id ": "55",
        "bookName": "Sự Kiến Tạo Xã Hội Về Thực Tại",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-su-kien-tao-xa-hoi-ve-thuc-tai.jpg?alt=media&token=fc84d87d-7498-44c0-b3dd-5f994c2b7974",
        "price": "210000",
        "title": "Như tựa đề của công trình, đây là một khảo luận về xã hội học nhận thức và điểm độc đáo của công trình này là nghiên cứu về tất cả các kiến thức, trong đó chú ý trước hết đến những “kiến thức đời thường” mà trước kia giới xã hội học thường bỏ quên do chỉ cho rằng đối tượng nghiên cứu của xã hội học nhận thức là những kiến thức, ý tưởng hoặc tư duy mang tính lý thuyết của con người.",
        "category": "Triết Học",
        "author": "Peter L. Berger - Thomas Luckmann",
    },
    {
        "id ": "56",
        "bookName": "Con Người Trong Thế Giới Tinh Thần",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-con-nguoi-trong-the-gioi-tinh-than.jpg?alt=media&token=3d19d787-c535-4e13-927f-d9e585bfeb58",
        "price": "170000",
        "title": "N. A. Berdyaev cho rằng không thể có bản diện cá nhân nếu không tồn tại cái đứng cao hơn nó, nếu không có cái thế giới trên núi để bản diện cá nhân leo lên. Hiện hữu của bản diện cá nhân đòi hỏi phải có hiện hữu của các giá trị siêu cá biệt. Từ nhân học ông đi đến hiện hữu của Thượng Đế. Nhưng N. A. Berdyaev bác bỏ quan niệm Thượng Đế như sức mạnh thống trị thế gian và sử dụng con người vốn là tạo vật của mình như phương tiện để tự vinh danh mình. Ông quan niệm một Thượng Đế-bản diện cá nhân mong mỏi con người-bản diện cá nhân đáp lại lời hiệu triệu của Người và Người có thể giao lưu tình yêu với nó. Thượng Đế bộc lộ bản thân mình trong thế giới tinh thần của con người, nhưng Thượng Đế không cai quản thế gian như một quân vương. N. A. Berdyaev tự xem mình là tín đồ Kitô giáo, nhưng không ràng buộc bản thân với bất cứ giáo hội nào. Ông cho rằng cuộc sống tôn giáo bao giờ cũng là cuộc sống cá nhân riêng tư trong thâm nhập vào chiều sâu của nó. Ông viết rằng từ thời thơ ấu ông đã xác định kiểu tôn giáo của ông là tinh thần nội tâm và tự do.",
        "category": "Triết Học",
        "author": "Nikolai Alexandrovich Berdyaev",
    },
    {
        "id ": "57",
        "bookName": "Cách Ta Nghĩ",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-cach-ta-nghi.jpg?alt=media&token=17de4b82-170e-4548-ac90-7fcd7cbad02f",
        "price": "180000",
        "title": "Cách ta nghĩcủa John Dewey nói về bản chất tư duy của con người. Thông qua những ví dụ hằng ngày, Dewey mô tả chi tiết các quy trình khác nhau của quá trình suy nghĩ và rèn luyện trí nghĩ. Ông cho rằng suy nghĩ là một hành động tự nhiên, việc dạy một người nào đó suy nghĩ là một việc bất khả. Tuy nhiên, có thể giúp phát triển tư duy của con người thông qua việc phát triển khả năng sáng tạo, sự tò mò và cách đặt câu hỏi. Để có thể làm như vậy, thay vì nhồi nhét kiến thức, chúng ta có nên tập trung vào việc tạo ra một môi trường kích thích tư duy sáng tạo.",
        "category": "Triết Học",
        "author": "John Dewey",
    },
    {
        "id ": "58",
        "bookName": "Bàn Về Tinh Thần Pháp Luật",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-ban-ve-tinh-than-phap-luat.jpg?alt=media&token=015c6c0d-b400-4ce6-82d0-7ce1072895c3",
        "price": "190000",
        "title": "“Bàn về tinh thần pháp luật”là tuyệt tác triết học củaMontesquieu, là một trong những tác phẩm vĩ đại trong lịch sử triết học chính trị và trong lịch sử luật học. Mục đích cuốn sách, như chính tác giả đã nêu, là: Trình bày những nguyên nhân quyết định nền pháp lý cho mỗi quốc gia; trình bày sự phù hợp cần thiết giữa luật lệ và chế độ cai trị của một nước; trình bày những quan hệ giữa các luật lệ với nhau. Ông đã phải mất gần 20 năm cho tác phẩm này.",
        "category": "Triết Học",
        "author": "Montesquieu",
    },
    {
        "id ": "59",
        "bookName": "Luận Lý Học",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-luan-ly-hoc.jpg?alt=media&token=1c62179b-d778-4d65-97dc-f16afffae9b4",
        "price": "185000",
        "title": "Logic hình thức còn được biết đến trong toán học như là logic ký hiệu là ngành khoa học nằm trong miền giao thoa giữa toán học và triết học tự nhiên. Logic hình thức sử dụng ký hiệu hình thức và các phép toán đại số cùng với các nguyên tắc nhất định về giá trị chân lý để nhằm xác định tính đúng đắn của các lập luận.",
        "category": "Triết Học",
        "author": "Trần Bích Lan",
    },
    {
        "id ": "60",
        "bookName": "Zarathustra Đã Nói Như Thế",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-zarathustra-da-noi-nhu-the.jpg?alt=media&token=d95e9aaf-41eb-4182-b5e8-5c23c54ea014",
        "price": "180000",
        "title": "Zarathustra đã nói như thếlà tác phẩm chính yếu của Nietzsche. Vừa thơ ca, vừa triết lý, nó ở giữa trung tâm tư tưởng Nietzsche: chính trong Zarathustra đã nói như thế Nietzsche đã tuyên bố và ca tụng Siêu nhân.",
        "category": "Triết Học",
        "author": "riedrich Nietzche",
    },
    {
        "id ": "61",
        "bookName": "Chủ Nghĩa Tự Do Truyền Thống",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-chu-nghia-tu-do-truyen-thong.jpg?alt=media&token=e30c2ef2-32c0-48f4-9dc2-a1f5ea585355",
        "price": "190000",
        "title": "Cuốn sách tương đối mỏng này có tầm quan trọng gấp nhiều lần sức tưởng tượng nếu chỉ nhìn vào độ dầy và ngôn ngữ khiêm nhường của nó. Đây là tác phẩm bàn về xã hội tự do, bàn về điều mà hiện nay có thể được gọi là “chính sách” đối nội và đối ngoại cho một xã hội như thế; và đặc biệt là bàn về những trở ngại và khó khăn, cả thực tế lẫn tưởng tượng, trên con đường thiết lập và giữ gìn hình thức tổ chức một xã hội như thế.",
        "category": "Triết Học",
        "author": "Ludwig von Mises",
    },
    {
        "id ": "62",
        "bookName": "Triết Học Nhân Sinh Của Tôi",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-triet-hoc-nhan-sinh-cua-toi.jpg?alt=media&token=463f6a81-dcdd-49fb-a28e-578de3379675",
        "price": "200000",
        "title": "Thế nào là triết học nhân sinh? Triết học nhân sinh có thể đem ra bàn luận không?\nCó câu “Thiên cơ bất khả lộ”, lại có câu “chỉ khả ý hội, bất khả ngôn truyền”, theo cách nói nhà Phật là “bất khả thuyết”.\nVì sao vậy?\nBởi ngôn ngữ là công cụ đắc lực, song cũng là cái bẫy. Một khi đã nói ra, viết ra, sẽ trở nên xơ cứng, thiếu sót, bị hiểu lệch lạc đi, bước vào quá trình “cứt chó hóa”.\nDám viết về triết học nhân sinh, triết học của đời người, thật dũng cảm thay! Cuốn sách trong tay bạn là tổng kết, đúc rút mấy chục năm trải nghiệm, cảm ngộ của một nhà văn lớn, cây đại thụ của văn đàn Trung Quốc  Vương Mông. Nội dung hàm súc triết lý cao song thể hiện dưới lối viết hóm hỉnh mà gần gũi, Triết học nhân sinh của Vương Mông đã trở thành một hiện tượng sách bán chạy trong năm đầu tiên xuất bản 2003, và đến nay vẫn được rất đông độc giả trẻ tuổi tìm đọc và tán thưởng.\nBạn sẽ tìm thấy ở đây 21 nguyên tắc trong quan hệ đối nhân, vì sao điều quan trọng nhất trong đời người là biết “không làm gì”, lời đáp cho “vô thường” và “hữu thường”, cùng “đại đạo vô thuật”…",
        "category": "Triết Học",
        "author": "Vương Mông",
    },
    {
        "id ": "63",
        "bookName": "Đại Cương Triết Học Trung Quốc  Liệt Tử Và Dương Tử",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-dai-cuong-triet-hoc-trung-quoc-liet-tu-va-duong-tu.jpg?alt=media&token=36932d0a-bc9b-4f40-ac00-e80e0cf911d3",
        "price": "210000",
        "title": "Ngay ở nước ta, cả trong giới tân học, tên Liệt tử cũng khá quen thuộc. Hầu hết chúng ta đều biết rằng tư tưởng của ông giống tư tưởng Lão, Trang và tuy chưa đọc cuốn Liệt tử vì chưa ai dịch nhưng ít nhất chúng ta cũng được biết dăm ba truyện rất lí thú trong cuốn đó thỉnh thoảng được trích dẫn trong các sách, báo, đặc biệt là trong bộ Cổ học tinh hoa của Nguyễn Văn Ngọc và Trần Lê Nhân, như truyện Bệnh quên, Mất dê, Người kiếm củi được con hươu, Lo trời đổ, Ngu Công dọn núi…, những truyện ai cũng phải nhận là những ngụ ngôn quí nhất của nhân loại.",
        "category": "Triết Học",
        "author": "Nguyễn Hiến Lê",
    },
    {
        "id ": "64",
        "bookName": "Trang Tử Nam Hoa Kinh",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-trang-tu-nam-hoa-kinh.jpg?alt=media&token=897ff6b8-75df-4bb0-945c-1079dbac9577",
        "price": "220000",
        "title": "Trang Tử (tiếng Hán: 莊子; ~365290 trước CN là một triết gia và tác giả Đạo giáo. Ông sống vào thời Chiến Quốc, thời kỳ đỉnh cao của các tư tưởng triết học Trung Hoa với Bách Gia Chư Tử.",
        "category": "Triết Học",
        "author": "Nguyễn Hiến Lê",
    },
    {
        "id ": "65",
        "bookName": "Hậu Hắc Học-Mặt Dày Tâm Đen",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-hau-hac-hoc-mat-day-tam-den.jpg?alt=media&token=be3a18fe-952c-4ee8-814c-5c30560f0029",
        "price": "190000",
        "title": "“Tôi viết “Hậu Hắc Học” vào cuối triều đại Mãn thanh, chia làm 3 tập: Tập đầu: Hậu Hắc Học; Tập giữa: Hậu Hắc kinh; tập cuối: Tạp lục Hậu Hắc truyện. Năm đầu của thời Dân Quốc đã đăng tải trên “Công luận nhật báo” ở Thành Đô. Độc giả có nhiều dư luận xôn xao, tôi cũng nhận được lời khuyên của bạn bè, tập giữa mới in nữa chừng đành phải dừng lại vậy. Trong thời gian ấy, tôi còn viết một bài: “Tôi hoài nghi các thánh nhân”, nhưng không tiện đăng lên báo chí. Về sau không biết bản thảo quăng đâu mất. Năm Dân Quốc thứ 16, theo ký ức mới viết lại cả hai bài, đưa vào tập sách. Năm Dân Quốc 23, một người bạn quên biết ở Bắc Kinh, theo ý chủ quan, đem ba tập tách ra in từng tập lẻ. Năm Dân Quốc 25 theo ý muốn của nhiều độc giả nên đã tái bản lần nữa. Năm Dân Quốc thứ 26, nhà xuất bản Quốc Dân báo Thành Đô đã đem tập đầu in thành một cuốn sách nhỏ và phát hành, do Đường Chu Phong và Trung Giang Tạ Thụ Thanh viết lời bạt .”",
        "category": "Triết Học",
        "author": "Lý Tôn Ngô",
    },
    {
        "id ": "66",
        "bookName": "Luận Về Yêu",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-luan-ve-yeu.jpg?alt=media&token=782a2252-07e3-4455-a4b3-0ea8da31ca88",
        "price": "",
        "title": "Cuốn sách này chứa đựng chính xác những gì lâu nay ta vẫn muốn biết về tình yêu: Không thiếu ảo tưởng nhưng cũng đầy sáng suốt, mê đắm nhưng biết giữ khoảng cách, nồng nhiệt và rất hài hước nhưng cùng lúc ngập tràn phân tích lạnh lùng. Chính khía cạnh “phân tích” này làm nên sự hấp dẫn nhất củaLuận về yêu, vì tác giả đã sử dụng những triết thuyết tưởng chừng khô cứng để tiếp cận tình yêu một cách thấu đáo, từ rất nhiều phương diện, kể cả những phương diện mà những người đang yêu thường muốn giấu kín. Luận về yêu, tác phẩm thời trẻ củaAlain de Botton, hiện nay là một nhà văn, triết gia và diễn giả nổi tiếng thế giới, còn đặc biệt hấp dẫn vì tùy theo tạng riêng của mình, độc giả có thể đọc nó như một tập tiểu luận sâu sắc, hoặc như một cuốn tiểu thuyết vô cùng hấp dẫn và không hề thiếu kịch tính.",
        "category": "Triết Học",
        "author": "Alain de Botton",
    },
    {
        "id ": "67",
        "bookName": "Giáo Trình Triết Học Mác  Lênin",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-giao-trinh-triet-hoc-mac-lenin.jpg?alt=media&token=a8e05b56-7fff-4916-a43e-a5403610253e",
        "price": "180000",
        "title": "Triết học Mác  Lênin hay học thuyết Mác-Lênin là một trong ba bộ phận cấu thành của chủ nghĩa Mác  Lênin, được Các Mác, Engels sáng lập vào thế kỷ thứ XIX, sau đó được Lênin và các nhà macxit khác phát triển thêm.Triết học Mác- Lê nin ra đời vào những năm 40 thế kỉ XIX và được phát triển gắn chặt với những thành tựu khoa học và thực tiễn trong phong trào cách mạng công nhân. Sự ra đời của triết học Mác-Lênin là một cuộc cách mạng thực sự trong lịch sử tư tưởng loài người, trong lịch sử triết học.",
        "category": "Triết Học",
        "author": "Nguyễn Ngọc Long- Nguyễn Hữu Vui",
    },
    {
        "id ": "68",
        "bookName": "Siêu Hình Học",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-sieu-hinh-hoc.jpg?alt=media&token=700c0c0b-22bc-4713-8b03-c587ffbae8d3",
        "price": "200000",
        "title": "Trong hai thập niên gần đây, một số lượng lớn những tác phẩm triết học đã ấn hành đều là những chuyên khảo và những khảo luận, mà tốt nhất nên coi như sách sử ký và phân loại. Kèm theo hiện tượng này là chuyện suy giảm việc ấn hành và sử dụng những tác phẩm triết học có tầm mức tổng quát hơn, ví dụ những sách giáo khoa. Điều này có thể là do những thay đổi thị hiếu của độc giả đương đại  giờ đây dường như họ cần được thoát khỏi lối tiếp cận hệ thống quá mức và học thuật quá cao của nhiều sách giáo khoa triết học. Mặt khác, khuynh hướng muốn chuyên hóa và muốn thủ đắc lối hiểu mang đậm tính lịch sử cũng như suy tư về các vấn đề triết học đã khiến chúng ta lơ là với một công tác quan trọng, đó là cung ứng cho những ai muốn đi vào lãnh vực triết học một kiến thức cơ bản có thể được dùng như nền tảng cho một sự hấp thụ phúc lợi nhiều nghiên cứu chuyên sâu. Quyển sách này là một bản giáo khoa về triết học cơ bản, đó là Siêu hình học  khoa học về hữu thể, như vẫn luôn được hiểu kể từ thời Permenides, Plato, Aristotle, và Thánh Thomas Aquinas cho đến ngày nay. Siêu hình học đặc biệt có giá trị trong thời chúng ta như triết học khai mở đến sự siêu việt của hữu thể sau nhiều thế kỷ bị hạn chế do chủ quan. Những nghiên cứu đương đại về hiện tượng luận, hiện sinh, và triết học phân tích, thêm một lần nữa đã làm dấy lên những vấn đề liên quan đến hữu thể. Mục tiêu của chúng tôi là trình bày cho độc giả những nguyên tắc siêu hình một cách sáng tỏ và thứ tự. Do đó, độc giả có thể giải quyết những vấn đề triết học nóng bỏng mà con người thời đại chúng ta phải đối mặt…",
        "category": "Triết Học",
        "author": "T.Alvira - L.Clavell - T.Melendo",
    },
    {
        "id ": "69",
        "bookName": "Ý Thức Mới Trong Văn Nghệ Và Triết Học",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-y-thuc-moi-trong-van-nghe-va-triet-hoc.jpg?alt=media&token=99b177da-932c-4a04-a203-73343dea6321",
        "price": "210000",
        "title": "Từ khá lâu tôi muốn chia sẻ với các bạn một cuốn sách nhưng tôi rất ngần ngại. Đó là cuốn “Ý thức mới trong văn nghệ và triết học” của Phạm Công Thiện. Sách này được xuất bản lần đầu tiên hình như vào năm 1968 hay 1969 gì đó, và tái bản năm 1970 tại Sài gòn. Với tôi ngày đó, đây là một cuốn sách “gây chấn động cho mình”. Đó là lần đầu tiên khi học lớp đệ tam (lớp 10 bây giờ) vào năm 1973. Nó đã theo tôi cho đến cuối những năm đại học. Rồi qua nhiều lần di chuyển, tôi không còn giữ được cuốn sách này. Mãi cho đến năm 2001, tôi tìm mua lại được ở những sạp bán sách cũ và từ khi biết thư viện này, tôi đã cố công gõ lại vào máy tính, mỗi ngày vài trang. Gõ với mục đích đề làm ebook chia sẻ, đồng thời gõ như một cách tìm lại một vài kỷ niệm ở đó; những kỷ niệm ở tuổi thiếu thời xa xôi của tôi ở một tỉnh lẻ ven miền trung Việt Nam. Tôi còn nhớ thời ấy của tôi, tôi có nhìn thấy rất nhiều những người đàn anh của tôi chuyền tay nhau đọc “Buồn Nôn” của Satre, “Kẻ xa lạ” của Camus hay những cuốn tiểu thuyết của Sagan. Tiếp đến lại thấy chuyền tay nhau Ý thức mới trong văn nghệ và triết học. Tôi cũng “bắt chước” những đàn anh của mình, cũng tìm một cuốn và ngấu nghiến đọc. Đúng như tôi đã nói, ngày đó, đọc xong cuốn sách này, với tôi như có một “chấn động” trong đầu. Những suy nghĩ vẩn vơ, nhiều khi mang màu sắc “triết học” thường có trong đầu mình. Tôi đã có lần suy nghĩ đến việc “bỏ học” đi lang thang giống như Rimbaud và cho giống … Phạm Công Thiện ! Tôi mơ tưởng liên hồi kỳ trận đến những chuyến tramway ở Paris, những ngọn đồi thơ mộng ở Monmatre, những góc phố New York … Ôi cái tuổi mới lớn của tôi, tôi bật cười khi nhớ đến nó. Và nói thật, nó còn ảnh hưởng ở tôi đến bây giờ. Hơn mười năm rồi, có lần tôi được ghé qua Paris  cái thành phố mà tôi hằng mơ ước được đến, dầu chỉ được một ngày ghé qua ! Rồi năm ngóai lại được dịp đến New York 3 ngày, giữa khu phố Harlem, ngồi uống một ly café kiểu Mỹ, dở òm, tôi nhớ liền đến cái câu của Henry Miller mà Phạm Công Thiện đã trích trong Ý thức mới trong văn nghệ và triết học: “Better a beggar in Paris than a millionaire in New York” và thầm nghĩ, cái ông Thiện này nói đúng quá chừng Tuy vậy, cái mà tôi nhận được nhiều nhất khi đọc cuốn sách là chính từ cuốn sách này, tôi phải tìm đọc cho kỳ được những cuốn sách mà Phạm Công Thiện đã nêu ra trong đó. Lùng sục bản tiếng Việt không có thì đành phải đi tìm bản tiếng Anh. Nào Tropic of Cancer, Tropic of Capricorn của Henry Miller, nào Hemingway, nào Nikos Kazanzaki, nào Chiến cầu trên sông Drina, hay thơ Rimbuad, Verlaine, hay Câu chuyện dòng sông của Hesse. Tôi đã biết đọc sách nhiều hơn, biết lựa sách hơn để đọc. Như cuốn Chiếc cầu trên sông Drina, tôi đọc đến cả hai tháng mới xong, vì mới đầu chịu, không thể nào “nuốt” trôi cái thể lọai “biên niên sử” được kể khề khà bởi Androvitch. Và sau đó, tôi có đọc lại đến mấy lần cuốn này, mới thấy là cuốn sách này hay thật là hay (Tôi đang cố công scan cuốn này một là để chia sẻ cùng các bạn, hai là “đền cái ơn tri ngộ” với bạn Tô Văn Hưng và thư viện ebook). Về chuyện đưa sách lên thư viện, lần này tôi xin được đưa lên chỗ VIP. Ban quản Trị có tòan quyền bỏ đi hay giữ lại. Hôm nọ đưa cuốn “Tuấn Chàng trai nước Việt” lên, tôi cũng ngại. Các bạn ạ, tôi ở tuổi “tri thiên mệnh” rồi, nên rắc rồi là điều tôi không mong muốn. Tuy nhiên tôi nghĩ, nếu chúng ta đọc được nhiều sách, và suy nghĩ về nó chín chắn thì chúng ta sẽ nhận lại được nhiều điều ký thú. Dĩ nhiên tôi không bao giờ cầu mong rằng có một cuốn sách nào mà mọi người điều đồng ý cả phải không? Kinh Thánh, hay Tam tạng kinh của Thích Ca còn có người nói là “tào lao” mà. Tôi viết hơi dài, nhưng không phải là lời giới thiệu về cuốn sách đâu. Tôi không đủ khả năng làm việc này. Các bạn có thể xem và bình phẩm Về tác giả Phạm Công Thiện, các bạn có thể tìm trên Google đề biết thêm. Tôi hì hục gõ cuốn này trong thời gian lâu nhưng không xong vì chuyện cơm áo nhọc nhằn. Thế rồi tôi phát hiện trên TLW có tôi mừng quá chừng nên down về và làm thành ebook để gửi các bạn",
        "category": "Triết Học",
        "author": "Phạm Công Thiện",
    },
    {
        "id ": "70",
        "bookName": "Dứt Tình",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-dut-tinh.jpg?alt=media&token=334945b0-8b29-4e2a-9cfa-f1f7dddde014",
        "price": "170000",
        "title": "Vũ Trọng Phụng là một nhà văn, nhà báo, một cây bút phóng sự với nhiều bài tiêu biểu. Năm 1930, ông có bài đăng trên Ngọ báo, nhưng lúc này tên tuổi ông chưa thực sự được chú ý trong giới văn học Việt Nam. Mãi đến 1931, vở kịnh Không một tiếng vang ra đời, thì mới bắt đầu gây được sự chú ý của bạn đọc. Năm 1934, Vũ Trọng Phụng có tiểu thuyết đầu tay “Dứt tình” (còn có tên khác là Bởi không duyên kiếp) đăng trên tờ Hải Phòng tuần báo. Với tiểu thuyết này, Vũ Trọng Phụng được khen là “ngòi bút tả chân thực đã khéo léo”.“Dứt tình”là cuốn tiểu thuyết mang tư tưởng định mệnh siêu hình.",
        "category": "Văn Học Việt Nam",
        "author": "Vũ Trọng Phụng",
    },
    {
        "id ": "71",
        "bookName": "Chiếc Ngai Vàng",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-chiec-ngai-vang.jpg?alt=media&token=4144f4e3-cb2c-4108-8b66-40005e38a34b",
        "price": "150000",
        "title": "Tiểu thuyết chủ đề lịch sử của nhà vănLan Khai được xuất bản vào năm 1937. Ông được đánh giálà một cây bút sung mãn, một nhà văn “đường rừng” sáng giá. Dù ở thể loại nào ngòi bút của ông vẫn thuyết phục được cảm tình và lí tính của độc giả.",
        "category": "Văn Học Việt Nam",
        "author": "Lan Khai",
    },
    {
        "id ": "72",
        "bookName": "Ván Bài Lật Ngửa",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-van-bai-lat-ngua.jpg?alt=media&token=2c6bf4ae-e7a7-41dc-9bdd-15e23e078536",
        "price": "180000",
        "title": "Trong ngày toàn thắng vĩ đại 30 tháng 4 nǎm 1975 kết thúc quá trình phấn đấu lâu dài của dân tộc có phần hy sinh đóng góp thầm lặng của những chiến sĩ tình báo. Mặt trận mà họ chiến đấu hầu hết không nổ súng, lại là nơi thử thách nghiêm khắc nhất bộ thần kinh cùng các đòi hỏi cao lòng dũng cảm, trí thông minh, sự nhạy bén.",
        "category": "Văn Học Việt Nam",
        "author": "Nguyễn Trương Thiên Lý",
    },
    {
        "id ": "73",
        "bookName": "Đống Rác Cũ  Trọn Bộ",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-dong-rac-cu-tron-bo.jpg?alt=media&token=605a261c-6fb8-404c-86fd-4a47ac3ce287",
        "price": "190000",
        "title": "Đống Rác Cũ phản ánh cuộc sống xã hội cũ bằng bút pháp hiện thực phê phán. Bạn đọc gặp ở Đống Rác Cũ những trang miêu tả xã hội, miêu tả con người từ thời kỳ trước những năm thứ 12 triều vua Bảo Đại, bằng bút pháp sắc sảo, với con mắt tinh đời, tính nhân đạo của nhà văn, cùng nụ cười của ông trước các thói dởm dở, những đạo đức giả của một bọn người mà thực chất bên trong lại chứa đựng một kho rác rưởi tởm lợm.",
        "category": "Văn Học Việt Nam",
        "author": "Nguyễn Công Hoan",
    },
    {
        "id ": "74",
        "bookName": "Quân Khu Nam Đồng",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-quan-khu-nam-dong.jpg?alt=media&token=b20ca5f5-2a79-4ff5-8d97-9f78fd4fe917",
        "price": "200000",
        "title": "Khu tập thể Nam Đồng là khu gia binh lớn nhất thủ đô Hà Nội, được hình thành cách đây hơn 50 năm. Là nơi ở của hơn 500 gia đình cán bộ quân đội trung, cao cấp, hơn 70 vị tướng đã từng sinh sống và trưởng thành từ Khu tập thể Nam Đồng, nhiều gia đình có cả hai thế hệ “tướng cha” và “tướng con”. Đây là một khu gia binh điển hình, một đại gia đình quân nhân thu nhỏ thời chiến và hậu chiến.",
        "category": "Văn Học Việt Nam",
        "author": "Bình Ca",
    },
    {
        "id ": "75",
        "bookName": "Sau Cành Violet",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-sau-canh-violet.jpg?alt=media&token=31ba6129-1daf-4962-a219-ee901ec7e8f6",
        "price": "175000",
        "title": "Cuốn sách không tái hiện lại cuộc chiến đấu giữa ta và địch trên chiến trường đầy bom đạn mà đưa người đọc đến với một trận tuyến thầm lặng. Đó là hình ảnh của những chiến sĩ tình báo (như Hồng Giang và Hoài Phương  hai nhân vật trong truyện). Các chiến sĩ của ta ngày đêm vượt khó khăn, hiểm nguy tiến hành các hoạt động phản gián ngay trong guồng máy chính quyền ngụy và tổ chức gián điệp CIA của Mỹ tại Sài Gòn. ",
        "category": "Văn Học Việt Nam",
        "author": "Ngô Tất Thắng",
    },
    {
        "id ": "76",
        "bookName": "Cuộc Đời Ngoài Cửa",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-cuoc-doi-ngoai-cua.jpg?alt=media&token=d34f4d9d-c071-4a9d-8aa9-de4bd9b2a749",
        "price": "180000",
        "title": "Trong vai một người viết tiểu thuyết,Nguyễn Danh Lamhẳn là mẫu nhà văn không thích, thậm chí rất dị ứng, việc cưng nựng chiều chuộng các nhân vật của mình. Từ những “Bến vô thường”, “Giữa vòng vây trần gian”, đến “Giữa dòng chảy lạc”, đã là thế. Và rồi đến cuốn tiểu thuyết mới nhất này, vẫn là thế. Nguyễn Danh Lam không thèm hạ cố ban cho nhân vật một danh tính rõ ràng. Cũng rất hiếm khi nhà văn gắn cho họ những nét phẩm chất tính cách hoặc những năng lực cá nhân trên mức trung bình. Đã vậy, anh lại hay đẩy các nhân vật vào những cảnh huống trớ trêu, những trạng thái sinh tồn nếu không bi đát thì cũng dở khóc dở cười.",
        "category": "Văn Học Việt Nam",
        "author": "Nguyễn Danh Lam",
    },
    {
        "id ": "77",
        "bookName": "Những Ngã Tư Và Những Cột Đèn",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-nhung-nga-tu-va-nhung-cot-den.jpg?alt=media&token=f9f50163-b969-4080-8e4d-93b116657164",
        "price": "200000",
        "title": "Chuyện rằng: vào giữa những năm 1960, nhà văn Trần Dần, khi đang trong hoàn cảnh hết sức ngặt nghèo của bản thân đã được một vài cán bộ công an hảo tâm tìm cách cho đi thâm nhập một số trại giam do Bộ Công an quản lý đang giam giữ những ngụy quân thời Pháp sau ngày tiếp quản Thủ đô. Kiểu đi như thế gọi là “đi thực tế” để khi về viết văn trên những cứ liệu của thực tế chuyến đi đó. Công thức ở đây là: cơ sở cung cấp tài liệu về một vấn đề cụ thể, nhà văn đi cho thấy, tiếp xúc cho biết, và cái viết ra thường chỉ là một báo cáo, một sơ đồ, dù có được vẽ vời thêm cho có vị văn chương.",
        "category": "Văn Học Việt Nam",
        "author": "Trần Dần",
    },
    {
        "id ": "78",
        "bookName": "Ngày Vui",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-ngay-vui.jpg?alt=media&token=ac864039-686f-481c-b348-2443694f8f62",
        "price": "210000",
        "title": "Ðặng Trần Huân sinh ngày 07 tháng 6 năm 1929 tại Bắc Ninh, cựu thiếu tá QLVNCH, làm việc tại Cục Tâm Lý Chiến, ngành thông tin báo chí. Khởi viết năm 1953. Ông là tác giả tập truyền cười nổi tiếng ” Chuyện Cấm Đàn Bà I & II (1969, 1970)” , rồi Chuyện Vợ Chồng (1970).",
        "category": "Văn Học Việt Nam",
        "author": "Đặng Trần Huân",
    },
    {
        "id ": "79",
        "bookName": "Tuyển Tập Truyện Ngắn Vũ Trọng Phụng",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-tuyen-tap-truyen-ngan-vu-trong-phung.jpg?alt=media&token=7c39b643-8e81-4003-a0bf-b31ead56a07e",
        "price": "160000",
        "title": "Nhắc đến Vũ Trọng Phụng người ta nghĩ ngay tới một nhà văn tài hoa nhưng bạc mệnh. Có năng khiếu nghệ thuật từ nhỏ, ông sáng tác từ rất sớm và thử nghiệm mình trên nhiều thể loại: viết báo, viết kịch, sáng tác truyện ngắn, truyện vừa, tiểu thuyết, phê bình văn học… Nhưng có thể nói, tiểu thuyết và phóng sự là hai thể loại thành công nhất của nhà văn tài hoa này. Vũ Trọng Phụng được báo giới thời bấy giờ mệnh danh là “ông vua phóng sự đất Bắc”, là “nhà tiểu thuyết trác việt”.",
        "category": "Văn Học Việt Nam",
        "author": "Vũ Trọng Phụng",
    },
    {
        "id ": "80",
        "bookName": "Con Hoang",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-con-hoang.jpg?alt=media&token=649891cb-b831-482d-bf7c-169bb43556dc",
        "price": "190000",
        "title": "Lại đêm nữa, bà đơn phương vùi khát thèm bằng trắng đêm giã gạo. Những đêm trăng quê yên tĩnh trải rộng miên man dài. Những đêm giã gạo toát mồ hôi, gió vừa đủ lạnh thấm lỗ chân lông gời gợi. Những đêm không chịu nổi, bà ôm chặt cái thân cối giã gạo, òa khóc cho hả lòng hả dạ, cho bớt tủi nhục cô đơn. Trong đêm, cái khúc gỗ nhãn làm thân cối giã gạo được bào nhẵn vuông tròn mịn màng hiển hiện như một thân thể đàn ông. Tại sao không cho bà được yêu thương, được ôm ấp, được giận hờn…",
        "category": "Văn Học Việt Nam",
        "author": "Lê Hồng Nguyên",
    },
    {
        "id ": "81",
        "bookName": "Đoạn Tình",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-doan-tinh.jpg?alt=media&token=fc4461ab-9e21-4b4b-85b7-7d76dfe14978",
        "price": "180000",
        "title": "Tiểu thuyết của ông bao quát những mảng hiện thực, những nét văn hóa đặc trưng của Nam bộ vào những thập niên đầu thế kỷ 20.Đó là sự tha hóa của con người trước sự lớn lên vùn vụt của đầu óc trọng thương, là số phận đáng thương của những thường dân rơi vào cảnh cùng quẫn, là những câu chuyện thế sự giàu chất nhân văn của những con người trên vùng đất mới…",
        "category": "Văn Học Việt Nam",
        "author": "Hồ Biểu Chánh",
    },
    {
        "id ": "82",
        "bookName": "Một Đứa Con Đã Khôn Ngoan",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-mot-dua-con-da-khon-ngoan.jpg?alt=media&token=927adf30-480b-499f-b688-bd62dbe46e13",
        "price": "190000",
        "title": "Trong truyệnMột đứa con đã khôn ngoan, nhà văn giáo dục trẻ em đức tính yêu lấy tiếng Việt. “Ta có tiếng nói riêng. Bổn phận ta là phải giữ lấy tiếng ta, vì tiếng ta tức là tinh thần nước ta”. Cậu bé Chỉ trong truyện này chỉ mê tiếng Pháp và cho rằng tiếng Việt không đủ để diễn tả hết mọi suy nghĩ và sự vật. Ngay cả lúc viết thư cho bạn, cậu cũng phải dùng thêm tiếng Pháp. Cậu (bố) của cậu bé Chỉ không đồng ý và phân tích cho cậu rằng: “Con thấy thiếu chứ tiếng ta không thiếu. Nếu thiếu chăng, thì nó thiếu ở ý mới, vật mới xưa kia không có. Còn những ý cũ vật cũ thì tiếng nước ta vẫn đủ như thường.",
        "category": "Văn Học Việt Nam",
        "author": "Nguyễn Công Hoan",
    },
    {
        "id ": "83",
        "bookName": "Những Mảnh Đời Đen Trắng",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-nhung-manh-doi-den-trang.jpg?alt=media&token=d6e630a2-e0ab-4ee1-847f-c6f68c1df1b8",
        "price": "170000",
        "title": "Những mảnh đời đen trắnglà một tác phẩm mạnh và dứt khoát. Là cuộc xung đột giữa hai tầng lớp xã hội, hai quan điểm sống khác nhau. Giữa hai thế hệ già và trẻ, giữa lớp người có quá khứ oai hùng và lớp ngưới không được quyền có quá khứ. Giữa lớp bần cố nông làm chủ tập thể, làm chủ tình thế và lớp trí thức tiểu tư sản “đầu thai nhầm thế kỷ, bị quê hương ruồng bỏ giống nòi khinh”. Cả hai giai tầng đều đáng thương mà không đáng trách. Một bên có khả năng nhận thức mà không được sử dụng. Một bên không có khả năng mà phải gánh vác những công việc quá sức mình.",
        "category": "Văn Học Việt Nam",
        "author": "Nguyễn Quang Lập",
    },
    {
        "id ": "84",
        "bookName": "Ăn Mày Dĩ Vãng",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-an-may-di-vang.jpg?alt=media&token=919a9459-479f-4906-9e40-c4234b62032c",
        "price": "160000",
        "title": "Hòa bình, những người lính kiêu dũng trong chiến tranh phần lớn đã “về vườn, ăn theo, núp váy vợ. Đứa thì say xỉn tối ngày nằm trên võng nắng; đứa thì lụi hụi trồng tỉa ngoài bưng, mở mồm là càu cạu; đứa thì thở dài phìn phịt giữa một bên là bầy con nhem nhuốc, một bên là thạp gạo chỉ còn cám mùn đọng quẩn dưới đáy; thằng kia sống trụi thùi lụi một mình, hỏi nhà cửa vợ con đâu chỉ giơ cái chai đế lên cười xệch xẹo”. Nhưng cũng có những người như Quân trước là cậu bé giao liên, nay là phó chủ tịch huyện, biết làm giàu cho quê hương và cho bản thân; hoặc như Tuấn, như Tám Tính đã hòa nhập tự nhiên với cuộc sống đời thường và không những thế còn vươn lên làm chủ cuộc sống mới. Trên hết vẫn là nhân vật Hai Hùng, “không vợ không con, không cắc bạc dính túi nhưng có mảnh quá khứ đập phập phồng trong lồng ngực”, với lý tưởng “Cuộc đời một thằng lính còn có gì khác hơn là khôn nguôi hướng về dĩ vãng và cầu mong cho dĩ vãng đó luôn trong lành chân thật”, một cá tính ít nhiều lạc điệu trong thời hiện tại, nơi “người ta đã hầu hết đều bảo nhau quay lưng lại với quá khứ”.",
        "category": "Văn Học Việt Nam",
        "author": "Chu Lai",
    },
    {
        "id ": "85",
        "bookName": "Đời Callboy",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-doi-callboy.jpg?alt=media&token=bb84b75c-a012-4c87-ace0-bf871b009bca",
        "price": "190000",
        "title": "Đời Callboy có những đoạn trần trụi khiến người ta hoài nghi về độ thật của nó và tự hỏi: “Xã hội thực sự là thế ư?”, nhưng nếu một lần tận mắt chứng kiến những gì đang xảy ra, mọi người sẽ hiểu rằng “Đời Callboy” của Nguyễn Ngọc Thạch đã đi đến được những góc khuất nhất của “nghề nghiệp” bị người đời coi khinh này.",
        "category": "Văn Học Việt Nam",
        "author": "Nguyễn Ngọc Thạch",
    },
    {
        "id ": "86",
        "bookName": "Giáo Trình Luật Hành Chính Việt Nam",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-giao-trinh-luat-hanh-chinh-viet-nam.jpg?alt=media&token=4f6e5ab8-da3c-4748-80df-fe3dbe46bcb5",
        "price": "190000",
        "title": "Luật hành chính Việt Nam là tổng thể những quy phạm pháp luật điều chỉnh những quan hệ chấp hành và điều chỉnh những quan hệ chấp hành và điều hành phát sinh, phát triển trong lĩnh vực tổ chức và hoạt động hành chính nhà nước. Những quy phạm pháp luật hành chính là công cụ pháp lý cơ bản để thực hiện quản lý nhà nước, thực thi quyền hành pháp  một trong ba loại quyền cơ bản được phân công, phối hợp giữa các cơ quan nhà nước trên cơ sở quyền lực nhà nước được thống nhất",
        "category": "Thư Viện Pháp Luật",
        "author": "Trường Đại Học Luật Hà Nội",
    },
    {
        "id ": "87",
        "bookName": "Luật Pháp",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-luat-phap.jpg?alt=media&token=acdcb525-7a88-4cc3-b386-7110fb59c9da",
        "price": "200000",
        "title": "Giống như nhiều người, Bastiat cho rằng chính phủ là mối đe doạ lớn nhất đối với tự do. Xin lưu ý, sự mạch lạc trong ngôn ngữ của ông giúp chúng ta nhận ra và hiểu những hành động xấu xa của chính phủ được hợp pháp hóa. Bastiat viết:“Chỉ cần xem luật pháp có lấy những cái thuộc về một số người nào đó và đem cho những người mà chúng không thuộc về. Chỉ cần xem luật pháp có làm lợi cho công dân này mà công dân khác phải trả giá bằng cách làm cái điều mà tự người công dân kia không thể làm mà không phạm tội”.Với cách mô tả chính xác như thế về hành động xấu xa được hợp pháp hóa, chúng ta không thể không kết luận rằng hầu hết các hoạt động của chính phủ, trong đó có chính phủ của chúng ta, là cướp bóc được hợp pháp hóa, hoặc dùng ngôn ngữ hiện đại là ăn cắp được hợp pháp hóa.",
        "category": "Thư Viện Pháp Luật",
        "author": "Claude Frédéric Bastiat",
    },
    {
        "id ": "88",
        "bookName": "Luật 101  Mọi Điều Bạn Cần Biết Về Pháp Luật Hoa Kỳ",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-luat-101-moi-dieu-ban-can-biet-ve-phap-luat-hoa-ky.jpg?alt=media&token=e4f5aade-776b-4837-8f48-36f86ad2bbe0",
        "price": "210000",
        "title": "Phiên bản đầu tiên và tái bản lần thứ hai của cuốn sách bán chạy nhất,Luật 101  Mọi điều bạn cần biết về pháp luật Hoa Kỳđã cung cấp cho độc giả một bức tranh sinh động và chân thực về hệ thống pháp luật của Hoa Kỳ. Và trong lần tái bản thứ ba này, Jay M. Feinman đã tiếp tục đưa ra cái nhìn tổng quát hơn và cập nhật đầy đủ về hệ thống pháp luật Hoa Kỳ, bao gồm tư liệu mới về các vụ kiện được Tòa án Tối cao Hoa Kỳ xét xử năm 2009, khía cạnh pháp lý về cuộc chiến chống khủng bố (kể cả những người bị giam giữ ở Guantanamo và cổng từ an ninh), và những tiến triển gần đây nhất của luật về Internet. Cuốn sách chứa đựng toàn bộ những điều hữu ích tương đương với chương trình năm học thứ nhất ở các trường đại học luật trên thế giới, bước đầu đưa người đọc đến với lối tư duy của một luật sư thực sự với khối lượng kiến thức của một khóa học bồi dưỡng cơ bản về nghề.",
        "category": "Thư Viện Pháp Luật",
        "author": "Jay M. Feinman",
    },
    {
        "id ": "89",
        "bookName": "Luật Doanh Nghiệp",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-luat-doanh-nghiep.jpg?alt=media&token=adddb404-4694-4052-9ea6-eeb853a5c016",
        "price": "220000",
        "title": "Ngày 26/11/2014, Quốc hội đã thông qua Luật Doanh nghiệp năm 2014 ( Luật số:68/2014/QH13), có hiệu lực kể từ 01/7/2015; Luật nàyquy định về việc thành lập, tổ chức quản lý, tổ chức lại, giải thể và hoạt động có liên quan của doanh nghiệp, bao gồm công ty trách nhiệm hữu hạn, công ty cổ phần, công ty hợp danh và doanh nghiệp tư nhân; quy định về nhóm công ty.",
        "category": "Thư Viện Pháp Luật",
        "author": "Quốc Hội Việt Nam",
    },
    {
        "id ": "90",
        "bookName": "Luật Thương Mại",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-luat-thuong-mai.jpg?alt=media&token=ffb7d1f2-bf6f-4b91-b3f0-21eed0c8e29a",
        "price": "210000",
        "title": "Ngày 14/6/2005, Quốc hội ban hànhLuật Thương mại số36/2005/QH11,áp dụng đối với các cá nhân hoạt động thường xuyên, độc lập; Các thương nhân hoạt động thương mại; Các tổ chức, cá nhân khác hoạt động có liên quan tới thương mại",
        "category": "Thư Viện Pháp Luật",
        "author": "Quốc Hội Việt Nam",
    },
    {
        "id ": "91",
        "bookName": "Luật Đất Đai",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-luat-dat-dai.jpg?alt=media&token=2040d73a-54a6-4983-a5bb-005919251a70",
        "price": "210000",
        "title": "Luật đất đai  Luật số45/2013/QH13điều chỉnh Chương trình xây dựng luật, pháp lệnh nhiệm kỳ Quốc hội khóa XIII, năm 2013 và Chương trình xây dựng luật, pháp lệnh năm 2014 do Quốc hội ban hành, sửa đổi bổ sung một số điều so vớiLuật Đất đai 2003, Luật Đất đai mới nhất này có 14 chương với 212 điều, tăng 7 chương và 66 điều.Luật có hiệu lực từ ngày 01/07/2014.",
        "category": "Thư Viện Pháp Luật",
        "author": "Quốc Hội Việt Nam",
    },
    {
        "id ": "92",
        "bookName": "Bộ Luật Lao Động",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-bo-luat-lao-dong.jpg?alt=media&token=ae798228-e2a0-43c0-8131-9e4d6fab1da5",
        "price": "210000",
        "title": "Bộ luật Lao động (Luật số: 10/2012/QH13) đã được Quốc hội khoá XIII thông qua ngày 18/6/2012, bắt đầu có hiệu lực từ 1/5/2013. Bộ luật lao động gồm 17 chương, 242 điều, tăng 19 điều so vớiBộ luật Lao động năm 2006.",
        "category": "Thư Viện Pháp Luật",
        "author": "Quốc Hội Việt Nam",
    },
    {
        "id ": "93",
        "bookName": "Luật Cán Bộ, Công Chức",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-luat-can-bo-cong-chuc.jpg?alt=media&token=839070ac-f20f-4f23-a653-a86149fa8090",
        "price": "210000",
        "title": "Luật cán bộ, công chứcđược Quốc hội nước Cộng hoà xã hội chủ nghĩa Việt Nam khoá XII, kỳ họp thứ 4 thông qua ngày 13 tháng 11 năm 2008. Luật cán bộ, công chức gồm 10 chương, 87 điều. Ngoài những quy định chung và điều khoản thi hành, Luật quy định cụ thể về các vấn đề: Nghĩa vụ, quyền của cán bộ, công chức; cán bộ ở Trung ương cấp tỉnh, cấp huyện; công chức ở Trung ương, cấp tỉnh, cấp huyện; cán bộ, công chức cấp xã; quản lý cán bộ, công chức; các điều kiện bảo đảm thi hành công vụ; thanh tra công vụ; khen thưởng và xử lý vi phạm.",
        "category": "Thư Viện Pháp Luật",
        "author": "Quốc Hội Việt Nam",
    },
    {
        "id ": "94",
        "bookName": "Điều Lệ Đảng Cộng Sản Việt Nam",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-dieu-le-dang-cong-san-viet-nam.jpg?alt=media&token=d7b52889-b4a0-48da-83ed-ae2d9e5fcb2b",
        "price": "210000",
        "title": "Đảng Cộng sản Việt Nam do đồng chí Hồ Chí Minh sáng lập và rèn luyện, đã lãnh đạo nhân dân tiến hành Cách mạng Tháng Tám thành công, lập nên nước Việt Nam Dân chủ Cộng hoà (nay là nước Cộng hoà Xã hội Chủ nghĩa Việt Nam), đánh thắng các cuộc chiến tranh xâm lược, xoá bỏ chế độ thực dân, phong kiến, hoàn thành sự nghiệp giải phóng dân tộc, thống nhất đất nước, tiến hành công cuộc đổi mới, xây dựng chủ nghĩa xã hội và bảo vệ vững chắc nền độc lập của Tổ quốc.",
        "category": "Thư Viện Pháp Luật",
        "author": "Quốc Hội Việt Nam",
    },
    {
        "id ": "95",
        "bookName": "Bộ Luật Dân Sự",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-bo-luat-dan-su.jpg?alt=media&token=cf520a27-7f7f-4c57-816a-611d76669b13",
        "price": "210000",
        "title": "Nội dung sách bao gồm các văn bản quy phạm pháp luật quy định vềđịa vị pháp lý, chuẩn mực pháp lý cho cách ứng xử của cá nhân, pháp nhân, chủ thể khác; quyền, nghĩa vụ của các chủ thể về nhân thân và tài sản trong các quan hệ dân sự, hôn nhân và gia đình, kinh doanh, thương mại, lao động (sau đây gọi chung là quan hệ dân sự).",
        "category": "Thư Viện Pháp Luật",
        "author": "Quốc Hội Việt Nam",
    },
    {
        "id ": "96",
        "bookName": "Luật An Ninh Mạng  2018",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-luat-an-ninh-mang-2018.jpg?alt=media&token=42d6f2ad-0b0c-4791-8507-ab12493972d3",
        "price": "210000",
        "title": "Luật an ninh mạng 2018 được Quốc hội thông qua ngày 12/6/2018 và bắt đầu có hiệu lực thi hành kể từ ngày 01/01/2019. Luật an ninh mạng gồm có 07 Chương và 43 Điều, trong đó, nêu ra các nguyên tắc bảo vệ an ninh mạng như sau:",
        "category": "Thư Viện Pháp Luật",
        "author": "Quốc Hội Việt Nam",
    },
    {
        "id ": "97",
        "bookName": "Bộ Luật Hình Sự",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-bo-luat-hinh-su.jpg?alt=media&token=7d201179-74c4-4750-b3b7-c9447b8ea9ee",
        "price": "200000",
        "title": "Bộ luật hình sự 2015 vừa được ban hành ngày 27/11/2015 với các quy định mới về tội phạm; những trường hợp loại trừ trách nhiệm hình sự; thời hiệu truy cứu trách nhiệm hình sự; hình phạt; các biện pháp tư pháp; quyết định hình phạt; chấp hành hình phạt; xóa án tích; pháp nhân thương mại phạm tội;…",
        "category": "Thư Viện Pháp Luật",
        "author": "Bộ Tư Pháp",
    },
    {
        "id ": "98",
        "bookName": "Truyện tranh Doremon",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-truyen-tranh-doremon.jpg?alt=media&token=ff56941c-7681-4028-b9a2-b6be58874a8f",
        "price": "120000",
        "title": "Bộ truyện được xem là huyền thoại của Nhật Bản. Nói về cuộc sống của một chú nhóc tên Nobita, tính tình hậu đậu và chú mèo máy Doremon đến từ thế kỉ 22 cùng những người bạn Xuka, Chaien, Xeko; để từ đó gây ra bao tiếng cười và rút ra những bài học ý nghĩa cho người xem !!",
        "category": "Truyện Tranh",
        "author": "Fujiko F. Fujio",
    },
    {
        "id ": "99",
        "bookName": "One Piece  Đảo Hải Tặc",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-one-piece-dao-hai-tac.jpg?alt=media&token=94667b82-fc65-468e-8610-f1518b9d7bf2",
        "price": "130000",
        "title": "One Piecelà câu truyện kể về Luffy và các thuyền viên của mình. Khi còn nhỏ, Luffy ước mơ trở thành Vua Hải Tặc. Cuộc sống của cậu bé thay đổi khi cậu vô tình có được sức mạnh có thể co dãn như cao su, nhưng đổi lại, cậu không bao giờ có thể bơi được nữa. Giờ đây, Luffy cùng những người bạn hải tặc của mình ra khơi tìm kiếm kho báu One Piece, kho báu vĩ đại nhất trên thế giới.",
        "category": "Truyện Tranh",
        "author": "Eiichiro Oda",
    },
    {
        "id ": "100",
        "bookName": "Truyện Tranh Doremon Plus",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-truyen-tranh-doremon-plus.jpg?alt=media&token=f59b8488-1976-401e-af08-1cf1de8d957c",
        "price": "120000",
        "title": "Doraemon Plus tập hợp những truyện ngắn chưa từng có trong bộ truyện Doraemon 45 tập đã rất quen thuộc với tất cả chúng ta. Đặc biệt Doraemon Plus tập 6 còn giới thiệu 21 truyện ngắn cực kì hấp dẫn và chưa từng được công bố!",
        "category": "Truyện Tranh",
        "author": "Fujiko F Fujio",
    },
    {
        "id ": "101",
        "bookName": "Đấm Phát Chết Luôn",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-dam-phat-chet-luon.jpg?alt=media&token=07659e3b-76a6-4d97-8f54-06d9869f65eb",
        "price": "140000",
        "title": "Manga thể loại siêu anh hùng với đặc trưng phồng tôm đấm phát chết luôn… Lol!!! Nhân vật chính trong Onepunch-man là Saitama, một con người mà nhìn đâu cũng thấy “tầm thường”, từ khuôn mặt vô hồn, cái đầu trọc lóc, cho tới thể hình long tong.",
        "category": "Truyện Tranh",
        "author": "Nhiều tác giả",
    },
    {
        "id ": "102",
        "bookName": "Thám Tử Lừng Danh Conan bản đẹp Gosho Aoyama",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/A%CC%89nh%20chu%CC%A3p%20ma%CC%80n%20hi%CC%80nh%202024-11-15%20215923.png?alt=media&token=8ab38c2c-9d58-4e64-bf2b-61ca20881176",
        "price": "150000",
        "title": "Thám Tử Lừng Danh Conan bản đẹp Gosho AoyamaThám tử lừng danh Conan(bản đẹp)hayDetective Conan, là một bộ truyện tranh trinh thám Nhật Bản của tác giả Aoyama Gōshō.",
        "category": "Truyện Tranh",
        "author": "Gosho Aoyama",
    },
    {
        "id ": "103",
        "bookName": "Dragon Quest  Dấu Ấn Rồng Thiêng",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-dragon-quest-dau-an-rong-thieng.jpg?alt=media&token=63cc7307-c850-4741-8ee1-56ed2d77ae71",
        "price": "130000",
        "title": "Dragon Quest  Dấu ấn rồng thiêng (Dragon Quest  Dai no Daiboken) cùng với 7 viên ngọc rồng là 2 bộ truyện ghi dấu ấn sâu đậm với những thế hệ bạn đọc 8x, 9x. Chắc hẳn vẫn còn rất nhiều người muốn tìm đọc lại bộ truyện này để nhớ lại những ký ức rất đẹp một thời. Nhân vật chính trong truyện là Dai no Daiboken  Dũng sĩ rồng Dai, từ một cậu bé hồn nhiên đã nhanh chóng trở thành Dũng sĩ diệt trừ ma quỷ, niềm hy vọng lớn nhất của thế giới loài người. Sát cánh cùng cậu là những học trò của Evan: Pop, Marm, Leona, Huynken.",
        "category": "Truyện Tranh",
        "author": "Sanjo Riku",
    },
    {
        "id ": "104",
        "bookName": "Siêu Quậy Teppi",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-sieu-quay-teppi.jpg?alt=media&token=8b433594-8b61-4c29-ba54-4ad4cc05107b",
        "price": "110000",
        "title": "Siêu quậy Teppi (Ore wa Teppei) là loạt manga do tác giả Chiba Tetsuya sáng tác và đăng trên tạp chí Weekly Shonen Magazine của Kodansha từ tháng 8 năm 1973 đến tháng 4 năm 1980.",
        "category": "Truyện Tranh",
        "author": "Tetsuya Chiba",
    },
    {
        "id ": "105",
        "bookName": "Bleach  Sứ Giả Thần Chết",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-bleach-su-gia-than-chet.jpg?alt=media&token=6199d6d9-8610-40b3-b80e-14bb74f1440d",
        "price": "120000",
        "title": "Bleachlà một chuỗi hành trình về Ichigo Kurosaki, cậu là một học sinh cấp ba với khả năng nhìn thấy linh hồn và một shinigami (thần chết) tên là Rukia Kuchiki, tình cờ gặp Ichigo khi đang săn lùng một linh hồn xấu được gọi là hollow (ác ma). Rukia bị thương trong cuộc chiến với linh hồn đó và bất đắc dĩ phải cho Ichigo năng lượng của mình. Thế là cuộc hành trình của Ichigo và Rukia bắt đầu từ đây.",
        "category": "Truyện Tranh",
        "author": "Kubo Tite",
    },
    {
        "id ": "106",
        "bookName": "Nanatsu No Taizai  Thất Hình Đại Tội",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-nanatsu-no-taizai-that-hinh-dai-toi.jpg?alt=media&token=b3e3cd15-7556-4a0b-a08c-63b090f574d4",
        "price": "130000",
        "title": "“Thất đại ác nhân”, một nhóm chiến binh có tham vọng lật đổ vương quốc Britannia, được cho là đã bị tiêu diệt bởi các “hiệp sĩ thánh chiến” mặc dù vẫn còn 1 số người cho rằng họ vẫn còn sống. 10 năm sau, Các hiệp sĩ thánh chiến đã làm 1 cuộc đảo chính và khống chế đức vua, họ trở thành người cai trị độc tài mới của vương quốc. Elizabeth, con gái duy nhất của nhà vua, đã lên đường tìm “thất đại ác nhân” để nhờ họ tái chiếm lại vương quốc. Công chúa có thành công trong việc tìm kiếm “thất đại ác nhân”, các “hiệp sĩ thánh chiến” sẽ làm gì để ngăn chăn cô? xem các chap truyện sau sẽ rõ.",
        "category": "Truyện Tranh",
        "author": "Suzuki Nakaba",
    },
    {
        "id ": "107",
        "bookName": "Toriko",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-toriko.jpg?alt=media&token=216be5d1-c9da-4851-9942-9c097cc840d9",
        "price": "120000",
        "title": "Toriko (トリコ) là loạt manga được thực hiện bởi Shimabukuro Mitsutoshi. Tác phẩm đã đăng trên tạp chí Weekly Shōnen Jump từ ngày 19 tháng 5 năm 2008. Cốt truyện xoay quanh Toriko một thợ săn ẩm thực với sức mạnh phi thường cùng kiến thức rất rộng về thiên nhiên đang tìm kiếm những món ăn ngon nhất thế giới để thêm vào danh sách các món ăn trong bữa ăn để đời của mình. Đi cùng anh là Komatsu một đầu bếp yếu đuối nhưng rất giỏi nấu nướng đang muốn nâng cao tay nghề của mình với những nguyên liệu kỳ lạ hiếm gặp mà Toriko kiếm được. Trên con đường của mình thì nhiều khác có cùng chí hướng cũng đã gia nhập nhóm để cùng nhau đi thám hiểm những vùng nguy hiểm trên thế giới để tìm kiếm những nguyên liệu nấu ăn độc đáo từ các sinh vật nguy hiểm cũng như chống lại các nhóm cạnh tranh khác.",
        "category": "Truyện Tranh",
        "author": "Shimabukuro Mitsutoshi",
    },
    {
        "id ": "108",
        "bookName": "Naruto",
        "image": "https://firebasestorage.googleapis.com/v0/b/bookchill-9ad45.appspot.com/o/nhasachmienphi-naruto.jpg?alt=media&token=5ca513cf-51fe-474b-b47a-24db18cfebc5",
        "price": "140000",
        "title": "Naruto( NARUTO—ナルト—?, tiếng Latinh làNARUTO) là manga Nhật Bản bằng văn bản và minh họa bởi tác giả Kishimoto Masashi. Nhân vật chính làUzumaki Naruto, một thiếu niên ồn ào, hiếu động, một ninja luôn muốn tìm cách khẳng định mình để được mọi người công nhận, rất muốn trở thành Hokage (Người đứng đầu làng lá Konoha)  người lãnh đạo ninja cả làng, được tất cả mọi người kính trọng.",
        "category": "Truyện Tranh",
        "author": "Kishimoto Masashi",
    },
]